### ISSUE TITLE
K9 throws random push errors

### ISSUE THREAD

**Issue by Thaodan** [k9mail/k-9#1057]
I'm using k9 with my Gmail account email seem to arrive instantly  but report these error mails from time to time:

K9-Mail version: 5.107
Device make: Huawei
Device model: Nexus 6P
Android version: 6.0.1

java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:705)
	at java.io.InputStream.read(InputStream.java:162)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:194)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
	at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:42)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2747)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2897)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:833)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3106)
	at java.lang.Thread.run(Thread.java:818) 

Sorry I couldn't provide more informations,  please feel free to ask for more

**Comment by cketti** [comment]
The connection timed out. This happens from time to time.

I created an issue to not report this to the user (at least not in K9mail-errors). See #1059
