### ISSUE TITLE
 error: ssl=0x999293c0:

### ISSUE THREAD

**Issue by Ed-Marc-Palacios** [k9mail/k-9#1087]
K9-Mail version: 5.006
Device make: asus
Device model: Nexus 7
Android version: 6.0.1

javax.net.ssl.SSLException: Read error: ssl=0x999293c0: I/O error during system call, Connection timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:705)
	at java.io.InputStream.read(InputStream.java:162)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:194)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
	at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:42)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2925)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:862)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3151)
	at java.lang.Thread.run(Thread.java:818)

**Comment by cketti** [comment]
See #1057
