### ISSUE TITLE
K9 crashes when compose action

### ISSUE THREAD

**Issue by github201407** [k9mail/k-9#1112]
### Expected behaviour

switch to MessageCompose Activity
### Actual behaviour

the app can`t work
### Steps to reproduce

click compose_action,then the app broken.
### Environment

K-9 Mail version:
V5.008
Android version:
SAMSUNG GT-I9300 Android 4.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
POP3
[MessageCompose](https://github.com/k9mail/k-9/blob/2a8b8555e70052abceafb4358918ff9aad4c50fc/k9mail/src/main/java/com/fsck/k9/activity/MessageCompose.java#L482)
`FATAL EXCEPTION: main
                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.MessageCompose}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2100)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125)
                                                               at android.app.ActivityThread.access$600(ActivityThread.java:140)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227)
                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                               at android.os.Looper.loop(Looper.java:137)
                                                               at android.app.ActivityThread.main(ActivityThread.java:4898)
                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
                                                               at dalvik.system.NativeStart.main(Native Method)
                                                            Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
                                                               at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:265)
                                                               at android.app.Activity.requestWindowFeature(Activity.java:3301)
                                                               at com.fsck.k9.activity.MessageCompose.onCreate**(MessageCompose.java:527)**
                                                               at android.app.Activity.performCreate(Activity.java:5184)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1083)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2064)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2125) 
                                                               at android.app.ActivityThread.access$600(ActivityThread.java:140) 
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1227) 
                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                               at android.os.Looper.loop(Looper.java:137) 
                                                               at android.app.ActivityThread.main(ActivityThread.java:4898) 
                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006) 
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773) 
                                                               at dalvik.system.NativeStart.main(Native Method) `

**Comment by cketti** [comment]
Are you using a rooted device with some tool installed that modifies the user interface?
If not, try uninstalling, then reinstalling the app.

**Comment by ahmadaamer6** [comment]
I am having this same issues on the latest version of K-9. I am not rooted... Please Fix

**Comment by ahmadaamer6** [comment]
I have a Debug Log from the crash if needed.
