### ISSUE TITLE
Sync problem since update to 5.010

### ISSUE THREAD

**Issue by coogor** [k9mail/k-9#1267]
### Expected behaviour
I'm using k9 since a couple of years, same accounts, but since upgrade to 5.010 Emails dont sync anymore with server

### Actual behaviour
K9 hangs on first folder

### Steps to reproduce
1. restart the app
2. check sync progress
3.

### Environment
K-9 Mail version:

Android version:
5.1.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment]
Please provide a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by coogor** [comment]
Debug log does not show anything, but the Folder K-9 errors:

K9-Mail version: 5.010
Device make: Sony
Device model: D6503
Android version: 5.1.1

com.fsck.k9.mail.MessagingException: IO Error
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.ioExceptionHandler(ImapStore.java:2208)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.appendMessages(ImapStore.java:2072)
	at com.fsck.k9.controller.MessagingController.processPendingAppend(MessagingController.java:2117)
	at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:1987)
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:975)
	at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
	at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketTimeoutException: Read timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
	at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:42)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readResponse(ImapStore.java:2847)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readResponse(ImapStore.java:2842)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.appendMessages(ImapStore.java:2012)
	... 7 more

This is strange as it happens across networks, and only for this device

**Comment by philipwhiuk** [comment]
It does look like nothing more than a timeout while trying to get a response...

It's trying to upload a copy of a local message to the server and being timed out when trying to get it.

If you don't mind losing the current synchronization steps in progress you can long-tap on the account and select 'Clear pending actions'.

We do have future work to try and re-design this process and give the user a bit more visibility on what exactly is being sync'd (a bit like the Send/Receive dialog you get on Outlook for example) - hence the milestone I've added this too. But as for the actual error we don't have much to work on.

**Comment by cketti** [comment]
@philipwhiuk Can you please create a new issue that contains information on what you want to improve. This issue should probably be closed.

**Comment by philipwhiuk** [comment]
@cketti I wrote some stuff on the wiki. To me it ties into the broader design overhaul as well.
