### ISSUE TITLE
 Failed to send some messages: RuntimeException: Nope 

### ISSUE THREAD

**Issue by cd2016** [k9mail/k-9#1373]
This seems to be a duplicate of #1206 and 1218, but it only started happening last night after an update to 5.108.

When trying to send a mail message, nothing is sent and instead I see the error " Failed to send some messages: RuntimeException: Nope" in my notifications and the email is placed in my DRAFTS folder.

K9 Log file below.

I am using a 1and1.com Imap server and have had no issues for 2 years until the update to 5.108 last night.

From: K9mail internal <*********>
Sent: May 11, 2016 12:40:24 PM EDT
Subject: Failed to send message
K9-Mail version: 5.108
Device make: samsung
Device model: SM-G900V
Android version: 5.0

java.lang.RuntimeException: nope
at com.fsck.k9.mailstore.BinaryMemoryBody.setEncoding(BinaryMemoryBody.java:36)
at com.fsck.k9.mail.internet.MimeMessage.setEncoding(MimeMessage.java:462)
at com.fsck.k9.mail.internet.MimeMessage.setUsing7bitTransport(MimeMessage.java:701)
at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:499)
at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:488)
at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3113)
at com.fsck.k9.controller.MessagingController$20.run(MessagingController.java:2993)
at com.fsck.k9.controller.MessagingController.run(MessagingController.java:257)
at java.lang.Thread.run(Thread.java:818)

**Comment by Valodim** [comment]
this issue is in all alpha versions we released this year, hopefully we'll have it fixed in the next.

still a duplicate. thanks for reporting anyways :)
