### ISSUE TITLE
SSL error with IMAP server after upgrading to Cyanogenmod 13

### ISSUE THREAD

**Issue by Shellfishgene** [k9mail/k-9#1487]
I always used K9 with my work IMAP account. Yesterday I upgraded my phone to Cyanogenmod 13, and K9 to the newest version. Now I get SSL errors when I try to connect to the server. It seems the same in the build in email app, however the "Outlook" email apps seems to work fine. I can get mail from the server fine with Thunderbird on Windows also.

Sending seems to work ok. Other email accounts (for example gmail) work fine using IMAP. 

### Environment
K-9 Mail version:
5.010
Android version:
Cyanogenmod 13.0
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP, SSL/TLS, normal password

### Error

K9-Mail version: 5.010
Device make: samsung
Device model: GT-I9300
Android version: 6.0.1

com.fsck.k9.mail.MessagingException: IO Error
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.ioExceptionHandler(ImapStore.java:2208)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:947)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.open(ImapStore.java:867)
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1041)
	at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
	at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
	at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396)
	at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:629)
	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:591)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2460)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.sendCommand(ImapStore.java:2872)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2921)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2902)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:858)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:904)
	... 6 more
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x4c52bbe0: Failure in SSL library, usually a protocol error
error:100c5410:SSL routines:ssl3_read_bytes:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/s3_pkt.c:972 0x4c04ba30:0x00000001)
error:100c009f:SSL routines:ssl3_get_server_hello:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/s3_clnt.c:750 0x43354757:0x00000000)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
	... 14 more

**Comment by cketti** [comment]
We disabled support for outdated/insecure SSL versions. Tell your admin to upgrade transport security on the mail server.
