### ISSUE TITLE
Permanent retreive of lails on imap

### ISSUE THREAD

**Issue by ncroiset** [k9mail/k-9#1546]
### Expected behavior
Get mails every 10 minutes After the launch of the smartphone

### Actual behavior
On the top of the screen I can show retrieve of mails in loop even if it is notice next retrieve in x minutes. I have a very big power consumption of the battery due to that bug.

### Environment
K-9 Mail version: 5.010

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by ncroiset** [comment]
I attach the logs I obtained :
K9-Mail version: 5.010
Device make: ZOPO
Device model: ZP720
Android version: 4.4.4

java.lang.Exception: Message count -1 for folder Drafts
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1113)
	at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
	at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
	at java.lang.Thread.run(Thread.java:848)

---------------------------

K9-Mail version: 5.010
Device make: ZOPO
Device model: ZP720
Android version: 4.4.4

com.fsck.k9.mail.AuthenticationFailedException: Command: AUTHENTICATE PLAIN; response: #3# [NO, [UNAVAILABLE], Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10)]
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.saslAuthPlain(ImapStore.java:2729)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2530)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.getPrefixedName(ImapStore.java:842)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher.getPrefixedName(ImapStore.java:2989)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:902)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher.internalOpen(ImapStore.java:2989)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3068)
	at
java.lang.Thread.run(Thread.java:848)


--

**Comment by cketti** [comment]
I don't think any of the errors are related to the behavior you're seeing. Try uninstalling, then reinstalling the app. If that doesn't get rid of the problem please create a new issue and provide a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by ncroiset** [comment]
I created this report after a reinstall.
So the problem still exist.

The main reason of this error is HERE :
com.fsck.k9.mail.AuthenticationFailedException: Command: AUTHENTICATE PLAIN; response: #3# [NO, [UNAVAILABLE], Maximum number of connections from user+IP exceeded

The apps try to connects multiple times (which is right because I have 3 IMAP accounts on the same machine), But instead of trying every 10 minutes like it is in the parameters, the apps goes in an infinite loop and try for these 3 accouns every time...
