### ISSUE TITLE
java.net.UnknownHostException: Unable to resolve host (using mobile connection)

### ISSUE THREAD

**Issue by zack-bergqvist** [k9mail/k-9#1552]
### Expected behavior
Sending and fetching mail possible when using mobile connection and when using Wi-Fi connection.

### Actual behavior
Sending mail and fetching mail fails when using mobile connection - everything works when using Wi-Fi. K9 is the only app that does not work when using mobile connection. The failure happens all the time so it is not dependent on a particular time or place or on the SMTP server. Background sync is "Never" so I manually fetch the mails from a SMTP server. As soon as I switch on Wi-Fi sending and fetching works normally.

K9mail-error:
_K9-Mail version: 5.010
Device make: LGE
Device model: Nexus 5
Android version: 6.0.1_

_com.fsck.k9.mail.MessagingException: Unable to get IMAP prefix
at com.fsck.k9.mail.store.ImapStore$ImapFolder.getPrefixedName(ImapStore.java:844)
at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:902)
at com.fsck.k9.mail.store.ImapStore$ImapFolder.open(ImapStore.java:867)
at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1041)
at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.UnknownHostException: Unable to resolve host "imap.web.de": No address associated with hostname
at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
at java.net.InetAddress.getAllByName(InetAddress.java:215)
at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2427)
at com.fsck.k9.mail.store.ImapStore$ImapFolder.getPrefixedName(ImapStore.java:842)
... 7 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Posix.android_getaddrinfo(Native Method)
at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
... 11 more_

### Steps to reproduce
1. Compose mail
2. Send it
__OR__
3. (Manual) Fetch mails

### Environment
K-9 Mail version: 5.010

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This is a network error. I don't see how this can be K-9 Mail's fault.

Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests.
