### ISSUE TITLE
[TLS] SSLv3 is required by device, but blocked by server

### ISSUE THREAD

**Issue by EtienneBruines** [k9mail/k-9#1594]
### Expected behavior
It should connect to an **IMAP** server which explicitely disabled SSLv3. 

### Actual behavior
It throws this error when connecting:
```
E/k9      (21935): Got exception while closing for exception for test:INBOX/Thread-1860
E/k9      (21935): java.lang.NullPointerException
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.reacquireWakeLockAndCleanUp(ImapFolderPusher.java:252)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.run(ImapFolderPusher.java:202)
E/k9      (21935): 	at java.lang.Thread.run(Thread.java:841)
E/k9      (21935): Got exception while idling for test:INBOX/Thread-1860
E/k9      (21935): com.fsck.k9.mail.MessagingException: IO Error
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapFolder.ioExceptionHandler(ImapFolder.java:1366)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:163)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.openConnectionIfNecessary(ImapFolderPusher.java:330)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.run(ImapFolderPusher.java:155)
E/k9      (21935): 	at java.lang.Thread.run(Thread.java:841)
E/k9      (21935): Caused by: javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x64fcc4e0: Failure in SSL library, usually a protocol error
E/k9      (21935): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x5e5c77e8:0x00000000)
E/k9      (21935): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:449)
E/k9      (21935): 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.<init>(OpenSSLSocketImpl.java:662)
E/k9      (21935): 	at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:633)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapConnection.setUpStreamsAndParserFromSocket(ImapConnection.java:228)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapConnection.startTLS(ImapConnection.java:312)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapConnection.upgradeToTls(ImapConnection.java:300)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapConnection.upgradeToTlsIfNecessary(ImapConnection.java:284)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:119)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapConnection.sendCommand(ImapConnection.java:640)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:623)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:612)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
E/k9      (21935): 	at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:145)
E/k9      (21935): 	... 3 more
E/k9      (21935): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x64fcc4e0: Failure in SSL library, usually a protocol error
E/k9      (21935): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x5e5c77e8:0x00000000)
E/k9      (21935): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/k9      (21935): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:406)
E/k9      (21935): 	... 15 more
```

### Steps to reproduce
1. Setup a server which disabled SSLv3 (feel free to try imap.sander-delmenhorst.net:993)
2. Enter settings in K9-Mail
3. When attempting to "verify" those settings, it'll fail. 

### Environment
K-9 Mail version:
Latest alpha release (5.111)

Android version: 
4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP with TLS (both SSL/TLS and STARTTLS aren't working, same certificate error). 

### Some other info
A lot of ciphers are supported, including those which are mentioned https://www.ssllabs.com/ssltest/viewClient.html?name=Android&version=4.4.2. On my desktop, I am actually able to connect to the server when explicitely using those certificates.

**Comment by cketti** [comment]
Make sure you only disable the SSLv3 protocol, not all ciphers supported by SSLv3.

See e.g. http://security.stackexchange.com/questions/70832/why-doesnt-the-tls-protocol-work-without-the-sslv3-ciphersuites

**Comment by steko** [comment]
What if I am only connecting to the server and have no control over its configuration?

**Comment by cketti** [comment]
We won't re-enable support for SSLv3. There are more modern and secure versions available for a very long time now. If you can't get the server administrator to fix the server configuration it's time to move on.

**Comment by steko** [comment]
> We won't re-enable support for SSLv3. 

Sure, I didn't mean suggesting that as an option. I'm just stuck with my employer's mail server. I'll suggest fixing the configuration pointing to the StackExchange answer you linked above, but I expect recursive levels of frustration and bureaucracy :disappointed_relieved:

**Comment by cketti** [comment]
If you believe talking about company politics is something users of an email client would enjoy, please feel free to use the [mailing list](http://groups.google.com/group/k-9-mail) to ask for advice.
