### ISSUE TITLE
Office 365 certificate issue

### ISSUE THREAD

**Issue by philipwhiuk** [k9mail/k-9#1757]
### Expected behavior
Should be able to send email to an account on Office 365

### Actual behavior

```
10-26 12:06:54.231 4972-4990/com.fsck.k9.debug E/k9: Failed to send message
    com.fsck.k9.mail.CertificateValidationException: Handshake failed
        at com.fsck.k9.mail.transport.SmtpTransport.open(SmtpTransport.java:416)
        at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:519)
        at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:512)
        at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3019)
        at com.fsck.k9.controller.MessagingController.access$1700(MessagingController.java:117)
        at com.fsck.k9.controller.MessagingController$21.run(MessagingController.java:2899)
        at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:206)
        at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:117)
        at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:175)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:429)
        at com.android.org.conscrypt.OpenSSLSocketImpl.waitForHandshake(OpenSSLSocketImpl.java:682)
        at com.android.org.conscrypt.OpenSSLSocketImpl.getInputStream(OpenSSLSocketImpl.java:644)
        at com.fsck.k9.mail.transport.SmtpTransport.open(SmtpTransport.java:245)
        at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:519) 
        at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:512) 
        at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3019) 
        at com.fsck.k9.controller.MessagingController.access$1700(MessagingController.java:117) 
        at com.fsck.k9.controller.MessagingController$21.run(MessagingController.java:2899) 
        at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:206) 
        at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:117) 
        at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:175) 
        at java.lang.Thread.run(Thread.java:761) 
     Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x72ff3f78c0: Failure in SSL library, usually a protocol error
    error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.c:192 0x733bf76f76:0x00000000)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
```

### Steps to reproduce

1. Configure the following account settings:

Server: smtp.office365.com
Security: SSL/TLS
Port: 587
Require sign in: Checked
Username: email@company.com
Authentication: Normal password

2. Attempt to send an email

### Environment
K-9 Mail version: master-branch code

Android version: 7.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

# Developer notes

Settings are taken from: https://support.office.com/en-gb/article/POP-and-IMAP-settings-for-Outlook-Office-365-for-business-7fc677eb-2491-4cbc-8153-8e7113525f6c?ui=en-US&rs=en-GB&ad=GB

The underlying error is that the SSL version number is wrong. I'm not sure if it is or not.

Here's a test with openssl s_client:

```
Philips-Air:k-9 philip$ openssl s_client -connect smtp.office365.com:587
CONNECTED(00000003)
1474:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/ssl/s23_clnt.c:618:

Philips-Air:k-9 philip$ openssl s_client -connect smtp.office365.com:587 -tls1
CONNECTED(00000003)
1475:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/ssl/s3_pkt.c:300:

Philips-Air:k-9 philip$ openssl s_client -connect smtp.office365.com:587 -ssl3
CONNECTED(00000003)
1476:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/ssl/s3_pkt.c:300:

Philips-Air:k-9 philip$ openssl s_client -connect smtp.office365.com:587 -ssl2
CONNECTED(00000003)
^C
```

Note that SSLv2 seems to work. The other options fail with a similar error to what we see in K-9.

**Comment by cketti** [comment]
You have to use STARTTLS in your openssl tests:
`openssl s_client -connect smtp.office365.com:587 -starttls smtp`

**Comment by philipwhiuk** [comment]
Hmm so that definitely looks okay and like crypto we ought to support:

```
    Protocol  : TLSv1
    Cipher    : AES256-SHA
```

**Comment by cketti** [comment]
Android should support that.
I just realized you used SSL/TLS for transport security. Make sure you use STARTTLS in K-9 Mail, too.

**Comment by philipwhiuk** [comment]
Hmm odd that Office365 expects SSL/TLS for IMAP but STARTSSL for SMTP. 

Anyway, that worked.
