### ISSUE TITLE
Body of messages not fetched

### ISSUE THREAD

**Issue by marmistrz** [k9mail/k-9#1794]
When using one of my accounts, some messages (which heavily use html) are not correctly fetched. I can see the title and some headers but the body is missing.

This happens only with one mail account.

The cause is probably this exception:
```
11-14 07:55:17.157 23585 23602 E k9      : synchronizeMailbox
11-14 07:55:17.157 23585 23602 E k9      : com.fsck.k9.mailstore.LockableDatabase$WrappedException: com.fsck.k9.mail.MessagingException: Error appending message: debian-devel-digest Digest V2016 #603
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder$12.doDbWork(LocalFolder.java:1090)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder$12.doDbWork(LocalFolder.java:1078)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder.storeSmallMessage(LocalFolder.java:1078)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.controller.MessagingController$12.messageFinished(MessagingController.java:1406)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mail.store.imap.ImapFolder.fetch(ImapFolder.java:770)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.controller.MessagingController.downloadSmallMessages(MessagingController.java:1393)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1196)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:953)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
11-14 07:55:17.157 23585 23602 E k9      : 	at java.lang.Thread.run(Thread.java:818)
11-14 07:55:17.157 23585 23602 E k9      : Caused by: com.fsck.k9.mail.MessagingException: Error appending message: debian-devel-digest Digest V2016 #603
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1326)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder$14.doDbWork(LocalFolder.java:1187)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder$14.doDbWork(LocalFolder.java:1182)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1182)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1109)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder$12.doDbWork(LocalFolder.java:1082)
11-14 07:55:17.157 23585 23602 E k9      : 	... 13 more
11-14 07:55:17.157 23585 23602 E k9      : Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.InputStream.close()' on a null object reference
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mail.internet.MimeUtility.closeInputStreamWithoutDeletingTemporaryFiles(MimeUtility.java:1060)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mail.internet.MessageExtractor.getTextFromTextPart(MessageExtractor.java:112)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mail.internet.MessageExtractor.getTextFromPart(MessageExtractor.java:55)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.crypto.MessageDecryptVerifier.isPartPgpInlineEncrypted(MessageDecryptVerifier.java:207)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.message.extractors.EncryptionDetector.containsInlinePgpEncryptedText(EncryptionDetector.java:34)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.message.extractors.EncryptionDetector.isEncrypted(EncryptionDetector.java:25)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.message.extractors.MessagePreviewCreator.createPreview(MessagePreviewCreator.java:31)
11-14 07:55:17.157 23585 23602 E k9      : 	at com.fsck.k9.mailstore.LocalFolder.saveMessage(LocalFolder.java:1251)
11-14 07:55:17.157 23585 23602 E k9      : 	... 19 more
11-14 07:55:17.173 23585 23602 E k9      : Failed synchronizing folder spamowe:INBOX @ Mon Nov 14 07:55:17 GMT+01:00 2016
```

### Environment
K-9 Mail version: 5.114

Android version: CM 13.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by marmistrz** [comment]
The `debian-devel digest` is not the only message that is missing, but the only one that is present in the logs

**Comment by cketti** [comment]
Can you please attach this message.

**Comment by marmistrz** [comment]
Sure, used the `save as` option in Thunderbird.
[debian-devel-digest Digest V2016 #603.eml.gz](https://github.com/k9mail/k-9/files/624434/debian-devel-digest.Digest.V2016.603.eml.gz)

**Comment by Valodim** [comment]
Fixed in the PR linked above! Your input has been most helpful, thanks @marmistrz
