### ISSUE TITLE
Using xoauth2, not able to send email from Gmail account with error : Negative SMTP reply: 530 5.5.1

### ISSUE THREAD

**Issue by kaushik-mota** [k9mail/k-9#1814]
I am using latest xoauth2 branch. Gmail account is configured without any issue. I can receive email successfully, but when trying to send email from app, it gives below error :

Failed to send message
```
                                                    com.fsck.k9.mail.transport.SmtpTransport$NegativeSmtpReplyException: Negative SMTP reply: 530 5.5.1  https://support.google.com/mail/?p=WantAuthError i76sm57306224pfk.89 - gsmtp
                                                        at com.fsck.k9.mail.transport.SmtpTransport.checkLine(SmtpTransport.java:657)
                                                        at com.fsck.k9.mail.transport.SmtpTransport.executeSimpleCommand(SmtpTransport.java:698)
                                                        at com.fsck.k9.mail.transport.SmtpTransport.executeSimpleCommand(SmtpTransport.java:662)
                                                        at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:536)
                                                        at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:512)
                                                        at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3143)
                                                        at com.fsck.k9.controller.MessagingController$21.run(MessagingController.java:3022)
                                                        at com.fsck.k9.controller.MessagingController.run(MessagingController.java:260)
                                                        at java.lang.Thread.run(Thread.java:818)
```

Version: xoauth2 branch
Android version : 6.01
Account type : IMAP

**Comment by philipwhiuk** [comment]
Is the password for sending email correct? Account settings -> Sending mail -> Outgoing server settings

**Comment by Kaushik-M** [comment]
I am using xoauth2 branch → https://github.com/k9mail/k-9/tree/xoauth2 and configuring account using Google auth. Everything was working fine before 2 days, but since 2 days I am having above error whenever I try to send email.

**Comment by Valodim** [comment]
(For the record, if you are using an experimental branch, it might be worth mentioning that from the get go instead of silently omitting the version number from the template ;) )

**Comment by Kaushik-M** [comment]
@Valodim : 👍 Thanks for pointing that out. I am not used to opening issue on GitHub. I have updated the title and description.

**Comment by philipwhiuk** [comment]
Even I don't run that code on my device and I wrote it! I believe there's possibly still a bug surrounding the refresh of tokens which I think is what you're hitting. I was always able to fix it by going into the settings and just forcing it to refresh by 'Next'-ing through the dialogs.

I intend to fix it when I get round to re-working the account setup and management code.

I intend to completely re-implement the way that XOAUTH2 is handled in the front-end because the current system can only ever support GMail and shortly after I developed it both Yahoo and Microsoft started pushing XOAUTH2 which meant @cketti and I agreed it would be unhelpful to merge it.

The only reason I didn't delete the branch is because I'll need to grab some of the code when I come to re-implement.

I've been putting it off because it requires time to sit down and rework large chunks of the UX and Account classes.

**Comment by Kaushik-M** [comment]
Thank you @philipwhiuk 👍 I will look into it and check if this is related to refresh token.

**Comment by kaeptmblaubaer1000** [comment]
The xoauth2 branch still exists... why haven't you implemented xoauth2 until now? There have been more than two years since you said this

**Comment by philipwhiuk** [comment]
I stopped using Android on my personal device. I guess it'll be done when someone else decides they want to work on it.
