### ISSUE TITLE
K-9 hangs while syncing

### ISSUE THREAD

**Issue by schwebke** [k9mail/k-9#1825]
### Expected behavior
fetch more messages after scrolling to end of inbox

### Actual behavior
K-9 hangs and won't recover until uninstalled and installed again.

### Steps to reproduce
1. install K-9
2. import settings and set password
3. open inbox
4. scroll down and fetch more messages
5. after two or three fetch more ops K-9 freezes

### Environment
K-9 Mail version:
5.010

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

[k9-log-3.txt](https://github.com/k9mail/k-9/files/619900/k9-log-3.txt)

**Comment by schwebke** [comment]
here the trace for the ANR:
[k9-trace.txt](https://github.com/k9mail/k-9/files/624218/k9-trace.txt)

**Comment by philipwhiuk** [comment]
DB work on the UI thread probably shouldn't be happening.

```
  at com.fsck.k9.mail.store.LocalStore$LocalFolder$1.doDbWork(LocalStore.java:1406)
  at com.fsck.k9.mail.store.LocalStore$LocalFolder$1.doDbWork(LocalStore.java:1398)
  at com.fsck.k9.mail.store.LockableDatabase.execute(LockableDatabase.java:283)
  at com.fsck.k9.mail.store.LocalStore$LocalFolder.open(LocalStore.java:1398)
  at com.fsck.k9.mail.store.LocalStore$LocalFolder.getVisibleLimit(LocalStore.java:1641)
  at com.fsck.k9.controller.MessagingController.loadMoreMessages(MessagingController.java:906)
  at com.fsck.k9.fragment.MessageListFragment.onItemClick(MessageListFragment.java:730)
  at android.widget.AdapterView.performItemClick(AdapterView.java:345)
  at android.widget.AbsListView.performItemClick(AbsListView.java:1547)
```

**Comment by schwebke** [comment]
after the ANR and ending the app, k9 does not recover. Even a reboot won't help. After the reboot the k9 background process drains battery loading one CPU core. I've attached the corresponding log entries. Seems k9 is waiting forever to access the database:

[k9-after-reboot.txt](https://github.com/k9mail/k-9/files/624406/k9-after-reboot.txt)

**Comment by cketti** [comment]
Is this still an issue with the latest K-9 Mail version?

**Comment by neufeind** [comment]
I didn't experience it anymore lately. Moved to a new phone with a fresh install and newer Android. Didn't occur or show any major delays for me.
