### ISSUE TITLE
Crash: NPE in MessageCompose.onDestroy()

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#1876]
Via Play Developer Console
App version: 5.200

```
java.lang.RuntimeException: Unable to destroy activity {com.fsck.k9/com.fsck.k9.activity.MessageCompose}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.fsck.k9.activity.compose.RecipientPresenter.onActivityDestroy()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3865)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3883)
	at android.app.ActivityThread.-wrap5(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.fsck.k9.activity.compose.RecipientPresenter.onActivityDestroy()' on a null object reference
	at com.fsck.k9.activity.MessageCompose.onDestroy(MessageCompose.java:536)
	at android.app.Activity.performDestroy(Activity.java:6422)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3852)
	... 9 more
```

**Comment by philipwhiuk** [comment]
During MessageCompose creation if we upgrade databases, the activity is finished before it's fully created.

```
        if (UpgradeDatabases.actionUpgradeDatabases(this, getIntent())) {
            finish();
            return;
        }
```

This means there's no RecipientPresenter to destroy, because it's not been created yet.
