### ISSUE TITLE
Crash: NPE in MessageCompose.onCreateOptionsMenu()

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#1898]
Via Play Developer Console
Version: 5.201

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.fsck.k9.Account.hasDraftsFolder()' on a null object reference
	at com.fsck.k9.activity.MessageCompose.onCreateOptionsMenu(MessageCompose.java:1030)
	at android.app.Activity.onCreatePanelMenu(Activity.java:3075)
	at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:621)
	at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:998)
	at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:323)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6873)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by philipwhiuk** [comment]
This is an odd one. 

`mAccount is null`. 

But if it is set null initially, we should have called `finish()` during `onCreate()`. One option is 'onAccountChosen' has provided a null account to switch to. We can just do a null check for that.

**Comment by cketti** [comment]
It looks like `onCreateOptionsMenu()` is called even though we call `finish()` in `onCreate()` when no accounts have been found.
