### ISSUE TITLE
Crash: NPE in LocalStore.getRawAttachmentInputStream()

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#1899]
Via Play Developer Console
Version: 5.200 or 5.201

```
java.lang.NullPointerException: Attempt to get length of null array
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:60)
	at com.fsck.k9.mailstore.LocalStore.getRawAttachmentInputStream(LocalStore.java:873)
	at com.fsck.k9.mailstore.LocalStore.writeSimplePartToOutputStream(LocalStore.java:857)
	at com.fsck.k9.mailstore.LocalStore.writeCursorPartsToOutputStream(LocalStore.java:746)
	at com.fsck.k9.mailstore.LocalStore.access$300(LocalStore.java:78)
	at com.fsck.k9.mailstore.LocalStore$16.doDbWork(LocalStore.java:722)
	at com.fsck.k9.mailstore.LocalStore$16.doDbWork(LocalStore.java:714)
	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
	at com.fsck.k9.mailstore.LocalStore.writeAttachmentDataToOutputStream(LocalStore.java:714)
	at com.fsck.k9.mailstore.LocalStore.access$100(LocalStore.java:78)
	at com.fsck.k9.mailstore.LocalStore$15.writeTo(LocalStore.java:706)
	at org.openintents.openpgp.util.ParcelFileDescriptorUtil$DataSourceTransferThread.run(ParcelFileDescriptorUtil.java:118)
```

**Comment by philipwhiuk** [comment]
`data` is only null (not set) if the Body is an instance of Multipart (`updateOrInsertMessagePart`). Are we mis-handling something?

**Comment by Valodim** [comment]
we go by `instanceof` in `updateOrInsertMessagePart`, and then load based on `MimeUtility.isMultipart(mimeType)`, it's quite possible there are discrepancies here. this is what happened in #1836, for example

**Comment by cketti** [comment]
Looks like we use `DataLocation.IN_DATABASE` for multiparts rather than `DataLocation.CHILD_PART_CONTAINS_DATA`. See https://github.com/k9mail/k-9/blob/977d15c1909fa476e157b0f1d55c8d200e9cb2e5/k9mail/src/main/java/com/fsck/k9/mailstore/LocalFolder.java#L1366

**Comment by Valodim** [comment]
We do! Why? :)

**Comment by cketti** [comment]
a) It feels wrong. The part does not contain any data, the child parts do.
b) In `writeCursorPartsToOutputStream()` the `writeSimplePartToOutputStream()` branch is taken which can't handle `Multipart` and will lead to the exception.

Do we rely on multiparts having `DataLocation.IN_DATABASE` or not having `DataLocation.CHILD_PART_CONTAINS_DATA` anywhere? Otherwise we can add another migration to fix this up and `writeCursorPartsToOutputStream()` should work just fine without modifications.

**Comment by Valodim** [comment]
I agree. I don't think there is currently any code that relies on this, and we can also do a migration that does `if (mimeType == multipart/* && dataLocation == IN_DATABASE) dataLocation = CHILD_PART_CONTAINS_DATA`
