### ISSUE TITLE
ClassCastException on IMAP sync #811

### ISSUE THREAD

**Issue by fkbreitl** [k9mail/k-9#2269]
Hi, I see the same problem of issue #811 `classcastexception: com.fsc` on my Inbox folder after a mail server was changed. Other folders look fine but I cannot receive new mail now.

K-9 Mail version: 5.203
Device Model: Samsung Galaxy S4
Android version: 5.0.1

I also found this problem mentioned at

http://grokbase.com/t/gg/k-9-mail/142prrhagm/classcastexception-com-fsc-error-on-some-folders

**Comment by philipwhiuk** [comment]
You should be able to see the full stack trace in the k9mail-errors folder for that account. It would be really useful if you could paste that here :)

**Comment by fkbreitl** [comment]
I just had a look, but my `K9mail-errors` folder is empty.

**Comment by philipwhiuk** [comment]
:-1:  We probably need a debug log then - if you're able to do it.

**Comment by fkbreitl** [comment]
It seems like the problem disappeared.
I still have the same version of K-9 Mail and didn't change anything but now I see all the latest mail!

**Comment by pdmholden** [comment]
I currently have this problem. Here is the output that got dumped into my k9mail-errors folder:

````
ClassCastException: com.fsck.k9.mail.store.imap.ImapList cannot be cast to java.lang.String

K9-Mail version: 5.206
Device make: HUAWEI
Device model: HUAWEI GRA-L09
Android version: 5.0

java.lang.ClassCastException: com.fsck.k9.mail.store.imap.ImapList cannot be cast to java.lang.String
	at com.fsck.k9.mail.store.imap.ImapList.getString(ImapList.java:36)
	at com.fsck.k9.mail.store.imap.ImapFolder.handleFetchResponse(ImapFolder.java:870)
	at com.fsck.k9.mail.store.imap.ImapFolder.fetch(ImapFolder.java:754)
	at com.fsck.k9.controller.MessagingController.fetchUnsyncedMessages(MessagingController.java:1317)
	at com.fsck.k9.controller.MessagingController.downloadMessages(MessagingController.java:1162)
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:951)
	at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:739)
	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
	at java.lang.Thread.run(Thread.java:831)
````

Some notes:

* This only happens on INBOX. All other folders can be refreshed without trouble.
* I had this problem a few months ago (around early March I believe, but I don't remember what version I was running). I believe at the time I re-installed the app and the problem went away.
* The problem crosses versions. I updated three days ago to 5.206. Whatever version I had before that also had the problem. I updated hoping it would solve the problem, but obviously it didn't.
* I can provide more debug output if needed.

**Comment by philipwhiuk** [comment]
It would be useful to see the verbose output showing the IMAP response received from the server. From the error it's not clear whether it's our parsing or the server's bad implementation (for example as seen in https://github.com/k9mail/k-9/issues/2474 )
