### ISSUE TITLE
All messages show "No message text" after upgrade to 5.204

### ISSUE THREAD

**Issue by wweich** [k9mail/k-9#2279]
### Expected behavior
Message content should be displayed.

### Actual behavior
"No message content" (German "Kein Nachrichtentext") ist displayed.

### Steps to reproduce
1. Upgrade to version 5.204
2. Load any message from before or after the upgrade
3.

### Environment
K-9 Mail version: 5.204

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (Dovecot 2.2.22)

**Comment by blue4s** [comment]
Same issue here. 
Android 6.1

Tried these fixes (didn't work) 
- reset k-9 app cache
- reset app cache and delete app Data and imported settings from backup and redownloaded messages (still: "no text") 
- deleted app and Data and imported settings file... Still no text

**Comment by Valodim** [comment]
Ugh, that's bad. Can any of you try to get a debug log of this using adb?

**Comment by rhari991** [comment]
`02-24 17:27:07.686 29780-29796/com.fsck.k9.debug E/k9: Error running command 'processPendingCommands'
                                                       android.database.sqlite.SQLiteException: no such column: arguments (code 1): , while compiling: SELECT id, command, arguments FROM pending_commands ORDER BY id ASC
                                                           at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                           at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                           at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                           at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                           at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                           at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                           at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                           at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1328)
                                                           at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1175)
                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1046)
                                                           at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1214)
                                                           at com.fsck.k9.mailstore.LocalStore$9.doDbWork(LocalStore.java:493)
                                                           at com.fsck.k9.mailstore.LocalStore$9.doDbWork(LocalStore.java:488)
                                                           at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:275)
                                                           at com.fsck.k9.mailstore.LocalStore.getPendingCommands(LocalStore.java:488)
                                                           at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:1710)
                                                           at com.fsck.k9.controller.MessagingController.access$800(MessagingController.java:115)
                                                           at com.fsck.k9.controller.MessagingController$13.run(MessagingController.java:1690)
                                                           at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
                                                           at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
                                                           at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
                                                           at java.lang.Thread.run(Thread.java:818)
02-24 17:27:14.437 29780-29803/com.fsck.k9.debug E/k9: Error while decoding message
                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.fsck.k9.ui.crypto.MessageCryptoAnnotations.isEmpty()' on a null object reference
                                                           at com.fsck.k9.mailstore.MessageViewInfoExtractor.extractMessageForView(MessageViewInfoExtractor.java:81)
                                                           at com.fsck.k9.ui.message.LocalMessageExtractorLoader.loadInBackground(LocalMessageExtractorLoader.java:55)
                                                           at com.fsck.k9.ui.message.LocalMessageExtractorLoader.loadInBackground(LocalMessageExtractorLoader.java:18)
                                                           at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
                                                           at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
                                                           at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
                                                           at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                           at java.lang.Thread.run(Thread.java:818)
`

**Comment by cketti** [comment]
Sorry for that.

5.204 was only distributed via Google Play's alpha channel and the GitHub releases page. I rolled back Google Play and removed the APK from GitHub. Uninstalling, then installing 5.203 will get you back to a working version.
I can't promise that an upcoming 5.205 will fix the problem if you had already upgraded to 5.204. Investigating now.

**Comment by cketti** [comment]
Looks like the database-related issue reported by @rhari991 is unrelated. 5.205 will be available shortly. Upgrading from 5.204 should work and keep all data intact.

**Comment by cketti** [comment]
Can you please check if 5.205 works for you: https://github.com/k9mail/k-9/releases/tag/5.205

**Comment by wweich** [comment]
Yes, 5.205 fixes the problem :)

**Comment by cketti** [comment]
Thanks
