### ISSUE TITLE
Folder list does not get updated anymore

### ISSUE THREAD

**Issue by konmax** [k9mail/k-9#2474]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
If I select Menu > Folders > Refresh Folders, I expect the list of folder to be synced with the server.

### Actual behavior
All "new" folders created on the server (I use an IMAP account via TLS) are not synced anymore. I have a folder list in K9 on my Android Samsung S5 device showing all folders created until last year, but new folders are not shown/added anymore. Maybe it has to do with the fact that I have more than 330 folders in this account?! I checked the server session logs and the folder list is sent from the server as expected.

### Steps to reproduce
1. Add a new folder on the IMAP server
2. select Menu > Folders > Refresh Folders

### Environment
K-9 Mail version: 5.206

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP via SSL/TLS

**Comment by philipwhiuk** [comment]
It should work and I'd be extreemely surprised if it were related to the number of folders.

Can you produce a K-9 debug log?

**Comment by konmax** [comment]
Sure. Can you tell me how?

Btw: Have the same issue on my Samsung tablet.

Thx
Konrad



Am 3. April 2017 16:31:56 GMT-04:00 schrieb Philip <notifications@github.com>:

**Comment by philipwhiuk** [comment]
There's some instructions here: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by konmax** [comment]
Thx. Will follow the instructions. Where do you want me to upload the debug file? Here via mail? Does it contain private data like passwords, mail texts and so on?

Konrad


Am 3. April 2017 17:10:20 GMT-04:00 schrieb Philip <notifications@github.com>:

**Comment by philipwhiuk** [comment]
There's an option to enable sensitive debugging - leave that off and it won't contain passwords. But it might contain emails received during the time the debugging is running. You can either email it me ( philip@whiuk.com ) or you can attach it to the issue.

**Comment by philipwhiuk** [comment]
Debugging this with @konmax via email:

```
com.fsck.k9.mail.MessagingException: Unable to get folder list.
	at com.fsck.k9.mail.store.imap.ImapStore.getPersonalNamespaces(ImapStore.java:156)
	at com.fsck.k9.controller.MessagingController.refreshRemoteSynchronous(MessagingController.java:430)
	at com.fsck.k9.controller.MessagingController$4.run(MessagingController.java:419)
	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: Expected 000d () but got 0028 (()
	at com.fsck.k9.mail.store.imap.ImapResponseParser.expect(ImapResponseParser.java:460)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.parseListResponse(ImapResponseParser.java:201)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readTokens(ImapResponseParser.java:140)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readUntaggedResponse(ImapResponseParser.java:71)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:42)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:30)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:88)
	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:634)
	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:620)
	at com.fsck.k9.mail.store.imap.ImapStore.listFolders(ImapStore.java:167)
	at com.fsck.k9.mail.store.imap.ImapStore.getPersonalNamespaces(ImapStore.java:143)
	... 6 more
```

Still trying to work out exactly why this happens.

**Comment by philipwhiuk** [comment]
This is a bug in the server you are using.

The IMAP spec specifies it should send:

`* LIST (\NoInferiors) "/" "Root/Subfolder/Folder()"`

because it contains brackets. Instead it is sending

`* LIST (\NoInferiors) "/" Root/Subfolder/Folder()`

which is invalid.
