### ISSUE TITLE
Can't connect to mail.vivaldi.net, never had any problem before I update Android to 7.1.2

### ISSUE THREAD

**Issue by repsorp** [k9mail/k-9#2523]
### Expected behavior
K9 should work the way it worked (perfectly for me) before I get a new mobile, update Android to 7.1.2 and make a fresh install of K9
Never had any problem with mail.vivaldi.net before

### Actual behavior
Not any problem with some of my e-mail accounts (gmail, me.com)
One is acting really weird with K9 (mail.vivaldi.net)
Everything working fine with Thunderbird (not any problem with mail.vivaldi.net)

### Steps to reproduce
1. Import parameters in my fresh installed K9 mail app
2. Can't connect to mail.vivaldi.net
3. Delete account, configure a new vivaldi account
4. Still doesn't work

### Environment
K9-Mail version: 5.207
Device make: LGE
Device model: Nexus 5X
Android version: 7.1.2

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

### K9mail-errors messages:

Objet : Push error for Sent

com.fsck.k9.mail.MessagingException: Unable to get IMAP prefix
	at com.fsck.k9.mail.store.imap.ImapFolder.getPrefixedName(ImapFolder.java:93)
	at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:142)
	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.openConnectionIfNecessary(ImapFolderPusher.java:330)
	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.run(ImapFolderPusher.java:155)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.io.IOException: readStringUntil(): end of stream reached
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStringUntil(ImapResponseParser.java:447)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.parseTaggedResponse(ImapResponseParser.java:287)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readTaggedResponse(ImapResponseParser.java:75)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:44)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:30)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:88)
	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:634)
	at com.fsck.k9.mail.store.imap.ImapConnection.login(ImapConnection.java:435)
	at com.fsck.k9.mail.store.imap.ImapConnection.saslAuthPlainWithLoginFallback(ImapConnection.java:391)
	at com.fsck.k9.mail.store.imap.ImapConnection.authenticate(ImapConnection.java:335)
	at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:121)
	at com.fsck.k9.mail.store.imap.ImapFolder.getPrefixedName(ImapFolder.java:91)

### ~~~

Objet : IOException: readStringUntil(): end of stream reached

com.fsck.k9.mail.MessagingException: Unable to get IMAP prefix
	at com.fsck.k9.mail.store.imap.ImapFolder.getPrefixedName(ImapFolder.java:93)
	at com.fsck.k9.mail.store.imap.ImapFolder.exists(ImapFolder.java:264)
	at com.fsck.k9.controller.MessagingController.processPendingAppend(MessagingController.java:1821)
	at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:1742)
	at com.fsck.k9.controller.MessagingController.access$800(MessagingController.java:115)
	at com.fsck.k9.controller.MessagingController$13.run(MessagingController.java:1690)
	at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:204)
	at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:115)
	at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:173)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.io.IOException: readStringUntil(): end of stream reached
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStringUntil(ImapResponseParser.java:447)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.parseTaggedResponse(ImapResponseParser.java:287)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readTaggedResponse(ImapResponseParser.java:75)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:44)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:30)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:88)
	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:634)
	at com.fsck.k9.mail.store.imap.ImapConnection.login(ImapConnection.java:435)
	at com.fsck.k9.mail.store.imap.ImapConnection.saslAuthPlainWithLoginFallback(ImapConnection.java:391)
	at com.fsck.k9.mail.store.imap.ImapConnection.authenticate(ImapConnection.java:335)
	at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:121)
	at com.fsck.k9.mail.store.imap.ImapFolder.getPrefixedName(ImapFolder.java:91)

### Log File:

[k9-log.txt](https://github.com/k9mail/k-9/files/968937/k9-log.txt)

**Comment by cketti** [comment]
The server responded with: `NO [UNAVAILABLE] Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10)` and then disconnects. Nothing we can do there.
