### ISSUE TITLE
K-9 crashes at inbox open on Android O

### ISSUE THREAD

**Issue by vt0r** [k9mail/k-9#2540]
K-9 crashed after clicking on the Inbox. Afterwards, it will crash on every startup.

### Expected behavior
K-9 opens the inbox.

### Actual behavior
K-9 crashes.

### Steps to reproduce
1. Choose the inbox after configuring an account
2. Profit?

### Environment
K-9 Mail version: 5.300-SNAPSHOT (built from current master)

Android version: 8.0 (Android O Developer Preview 2)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

```
05-17 22:55:03.781 E/AndroidRuntime(21282): FATAL EXCEPTION: main
05-17 22:55:03.781 E/AndroidRuntime(21282): Process: com.fsck.k9, PID: 21282
05-17 22:55:03.781 E/AndroidRuntime(21282): java.lang.LinkageError: Method android.view.LayoutInflater com.fsck.k9.fragment.MessageListFragment.getLayoutInflater() overrides final method in class Landroid/app/Fragment; (declaration of 'com.fsck.k9.fragment.MessageListFragment' appears in /data/app/com.fsck.k9-8rLXJQdRANND4GVTfWN6Mg==/base.apk)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at com.fsck.k9.activity.MessageList.actionDisplaySearch(MessageList.java:103)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at com.fsck.k9.activity.Accounts.onOpenAccount(Accounts.java:683)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at com.fsck.k9.activity.Accounts.onItemClick(Accounts.java:1239)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at android.widget.AdapterView.performItemClick(AdapterView.java:317)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3134)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at android.widget.AbsListView$3.run(AbsListView.java:4049)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at android.os.Handler.handleCallback(Handler.java:769)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at android.os.Looper.loop(Looper.java:164)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at android.app.ActivityThread.main(ActivityThread.java:6535)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at java.lang.reflect.Method.invoke(Native Method)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
05-17 22:55:03.781 E/AndroidRuntime(21282): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by philipwhiuk** [comment]
I think this is a bug in Android O as we aren't actually overriding that method.

**Comment by cketti** [comment]
We do have a method `getLayoutInflater()` in `MessageListFragment`. Renaming it should solve the problem.

**Comment by philipwhiuk** [comment]
Yeah I goofed and looked and the wrong file.

Should be a simple fix then

**Comment by vt0r** [comment]
Changed the title and updated the issue description to better describe the actual issue. This looks super easy to me, so I'll take a crack at a rename PR if nobody has any objections. Any opinions on the new name? I was thinking something like `getLayoutInflater2()` lol

**Comment by philipwhiuk** [comment]
Well try just deleting it. The new method seems like it might do what we want.

If not `getOriginalLayoutInflater()` seems to match what we actually mean.
