### ISSUE TITLE
crash caused by OOM when open an big email with about 2 million characters

### ISSUE THREAD

**Issue by liujiangshuai** [k9mail/k-9#2696]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
open an big email with about 2 million characters

### Actual behavior
crash caused by OOM
log:
`FATAL EXCEPTION: main
                                                                   Process: com.fsck.k9.debug, PID: 10098
                                                                   java.lang.OutOfMemoryError: Failed to allocate a 83877900 byte allocation with 16777216 free bytes and 51MB until OOM
                                                                       at dalvik.system.VMRuntime.newUnpaddedArray(Native Method)
                                                                       at com.android.internal.util.ArrayUtils.newUnpaddedArray(ArrayUtils.java:69)
                                                                       at android.text.StaticLayout.out(StaticLayout.java:525)
                                                                       at android.text.StaticLayout.generate(StaticLayout.java:423)
                                                                       at android.text.DynamicLayout.reflow(DynamicLayout.java:285)
                                                                       at android.text.DynamicLayout.<init>(DynamicLayout.java:171)
                                                                       at android.widget.TextView.makeSingleLayout(TextView.java:6408)
                                                                       at android.widget.TextView.makeNewLayout(TextView.java:6306)
                                                                       at android.widget.TextView.assumeLayout(TextView.java:6207)
                                                                       at android.widget.TextView.onPreDraw(TextView.java:4921)`
### Environment
K-9 Mail version:

Android version:5.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
I believe this is no longer an issue.
