### ISSUE TITLE
[5.300] Unable to check mail, Command: NAMESPACE; respons

### ISSUE THREAD

**Issue by rancidfrog** [k9mail/k-9#2799]
Outlook IMAP
Unable to check inbox all of a sudden using k9mail 5.300
It was working, I am able to connect on browser, but all of a sudden I am getting `Command: NAMESPACE; respons` whenever I refresh outlook account.
Other accounts work fine, though.

```

09-27 12:15:16.515  1439  2929 D ActivityTrigger: ActivityTrigger activityStopTrigger
09-27 12:15:16.721 12544 12567 V ImapResponseParser: conn237674745<<<#null# [CAPABILITY, IMAP4, IMAP4rev1, AUTH=PLAIN, AUTH=XOAUTH2, SASL-IR, UIDPLUS, MOVE, ID, UNSELECT, CHILDREN, IDLE, NAMESPACE, LITERAL+]
09-27 12:15:16.722 12544 12567 V ImapResponseParser: conn237674745<<<#1# [OK, CAPABILITY completed.]
09-27 12:15:16.726 12544 12567 D ImapConnection: Saving [SASL-IR, NAMESPACE, MOVE, AUTH=XOAUTH2, IDLE, IMAP4, UNSELECT, ID, IMAP4REV1, LITERAL+, UIDPLUS, CHILDREN, AUTH=PLAIN] capabilities for conn237674745
09-27 12:15:16.728 12544 12567 V ImapConnection: conn237674745>>> 2 AUTHENTICATE PLAIN
09-27 12:15:17.029 12544 12567 V ImapConnection: conn237674745<<<#+# []
09-27 12:15:20.303 12544 12567 V ImapResponseParser: conn237674745<<<#2# [OK, AUTHENTICATE completed.]
09-27 12:15:20.304 12544 12567 I ImapConnection: Did not get capabilities in post-auth banner, requesting CAPABILITY for conn237674745
09-27 12:15:20.306 12544 12567 V ImapConnection: conn237674745>>> 3 CAPABILITY
09-27 12:15:20.678 12544 12567 V ImapResponseParser: conn237674745<<<#null# [CAPABILITY, IMAP4, IMAP4rev1, AUTH=PLAIN, AUTH=XOAUTH2, SASL-IR, UIDPLUS, MOVE, ID, UNSELECT, CLIENTACCESSRULES, CLIENTNETWORKPRESENCELOCATION, BACKENDAUTHENTICATE, CHILDREN, IDLE, NAMESPACE, LITERAL+]
09-27 12:15:20.679 12544 12567 V ImapResponseParser: conn237674745<<<#3# [OK, CAPABILITY completed.]
09-27 12:15:20.679 12544 12567 D ImapConnection: Saving [SASL-IR, NAMESPACE, CLIENTNETWORKPRESENCELOCATION, AUTH=XOAUTH2, CLIENTACCESSRULES, BACKENDAUTHENTICATE, IMAP4REV1, ID, LITERAL+, MOVE, IDLE, IMAP4, UNSELECT, UIDPLUS, CHILDREN, AUTH=PLAIN] capabilities for conn237674745
09-27 12:15:20.679 12544 12567 I ImapConnection: pathPrefix is unset and server has NAMESPACE capability
09-27 12:15:20.680 12544 12567 V ImapConnection: conn237674745>>> 4 NAMESPACE09-27 12:15:21.023 12544 12567 V ImapResponseParser: conn237674745<<<#4# [BAD, User is authenticated but not connected.]
09-27 12:15:21.031 12544 12567 E ImapFolder: Unable to open connection for D:INBOX/MessagingController/conn237674745
09-27 12:15:21.031 12544 12567 E ImapFolder: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: NAMESPACE; response: #4# [BAD, User is authenticated but not connected.]
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:118)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:730)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:716)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapConnection.handleNamespace(ImapConnection.java:623)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapConnection.retrievePathPrefixIfNecessary(ImapConnection.java:613)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:134)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapConnection.sendCommand(ImapConnection.java:769)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:727)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:716)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:145)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.mail.store.imap.ImapFolder.open(ImapFolder.java:114)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:817)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:721)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:211)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:129)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:180)
09-27 12:15:21.031 12544 12567 E ImapFolder:    at java.lang.Thread.run(Thread.java:761)
09-27 12:15:21.036 12544 12567 E MessagingController: synchronizeMailbox
09-27 12:15:21.036 12544 12567 E MessagingController: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: NAMESPACE; response: #4# [BAD, User is authenticated but not connected.]
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:118)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:730)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:716)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapConnection.handleNamespace(ImapConnection.java:623)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapConnection.retrievePathPrefixIfNecessary(ImapConnection.java:613)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:134)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapConnection.sendCommand(ImapConnection.java:769)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:727)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:716)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:145)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapFolder.open(ImapFolder.java:114)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:817)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.controller.MessagingController$9.run(MessagingController.java:721)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:211)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:129)
09-27 12:15:21.036 12544 12567 E MessagingController:   at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:180)
09-27 12:15:21.036 12544 12567 E MessagingController:   at java.lang.Thread.run(Thread.java:761)
09-27 12:15:21.084 12544 12567 V TracingPowerManager$Tra: TracingWakeLock for tag FolderList checkMail / id 101: releasing after 6170 ms, timeout = 600000 ms
09-27 12:15:21.119 12544 12567 V LockableDatabase: LockableDatabase: Transaction ended, took 15 ms / com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1285)
09-27 12:15:21.126 12544 12567 E MessagingController: Failed synchronizing folder D:INBOX @ Wed Sep 27 12:15:21 GMT+03:00 2017
09-27 12:15:21.126 12544 12567 I MessagingController:  Command 'synchronizeMailbox' completed
09-27 12:15:21.126 12544 12567 I MessagingController: Running command 'sendPendingMessages', seq = 39 (background priority)
09-27 12:15:21.128 12544 12567 I MessagingController:  Command 'sendPendingMessages' completed
```

**Comment by rancidfrog** [comment]
This only happens on hotmail account. I have an outlook alias and it works fine. A little strange. Tried account setting for fetching mail, but same error:￼

**Comment by rancidfrog** [comment]
All of a sudden working again.
Issue with server side , perhaps?
