### ISSUE TITLE
Many automated tests in k9mail.src.test.java.com.fsck.k9 fail

### ISSUE THREAD

**Issue by jyn514** [k9mail/k-9#2866]
### Expected behavior
Automated tests should pass.

### Actual behavior
At least 196 of the automated tests fail for various reasons. About half are due to OutOfMemoryErrors (shown below), which are probably more to do with my laptop than anything else. There are many others failing as well -   
MessagingControllerTest fails with "Actual invocation has different arguments" and "Wanted but not invoked: transport.sendMassage(localMessageToSend1)";   
WearNotificationsTest fails with "Unable to find resource ID #0x7f0702d7 in packages [android, org.robolectric.default]";  
IdentityHelperTest fails with "java.lang.NoClassDefFoundError: Could not initialize class android.os.Environment";  
LockScreenNotificationTest fails with a null pointer exception;  
HtmlConverterTest fails with "java.util.ServiceConfigurationError: org.robolectric.internal.ShadowProvider: Provider org.robolectric.Shadows not a subtype";
various other tests fail.

Some tracebacks:
    MessagingControllerTest
    Wanted but not invoked:
    transport.sendMessage(localMessageToSend1);
    -> at com.fsck.k9.controller.MessagingControllerTest.sendPendingMessagesSynchronous_shouldSendMessageUsingTransport(MessagingControllerTest.java:544)
    Actually, there were zero interactions with this mock.

Also MessageControllerTest:
    Actual invocation has different arguments:
    localMessageToSend1.setFlag(
        X_SEND_IN_PROGRESS,
        true
    );
    -> at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:2604)

WearNotificationsTest:
    android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f0702d7 in packages [android, org.robolectric.default]

	at org.robolectric.shadows.ShadowAssetManager.getResName(ShadowAssetManager.java:868)
	at org.robolectric.shadows.ShadowAssetManager.resolveResourceValue(ShadowAssetManager.java:676)
	at org.robolectric.shadows.ShadowAssetManager.resolve(ShadowAssetManager.java:636)
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:630)
	at org.robolectric.shadows.ShadowAssetManager.getResourceText(ShadowAssetManager.java:226)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:295)
	at android.content.res.Resources.getString(Resources.java:385)
	at android.content.Context.getString(Context.java:377)
	at com.fsck.k9.notification.WearNotifications.addMarkAllAsReadAction(WearNotifications.java:59)
	at com.fsck.k9.notification.WearNotifications.addSummaryActions(WearNotifications.java:43)
	at com.fsck.k9.notification.WearNotificationsTest.testAddSummaryActionsWithDeleteAllActionEnabled(WearNotificationsTest.java:167)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:538)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:339)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:259)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:41)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:199)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

### Steps to reproduce
1. Run most automated tests in k9mail.src.test.java.com.fsck.k9

### Environment
K-9 Mail version: master (as of 2017-10-26, commit `27bc562ebe37bc139b84c13142681dbfe5640688`)

Android version: N/A

Account type (IMAP, POP3, WebDAV/Exchange): N/A

**Comment by philipwhiuk** [comment]
They don't fail on the build server. So the problem is most likely your setup (e.g. not allocating enough memory to Android Studio)

**Comment by philipwhiuk** [comment]
As for the resource problem, the issue is setting it up to run from the module directory not the project. It's a flaw in Android Studio.

If you run ./gradlew test you will find they all pass.
