### ISSUE TITLE
Import settings crashes on older phones

### ISSUE THREAD

**Issue by jyn514** [k9mail/k-9#2935]
### Expected behavior
During onboarding, I hit 'Import Settings and Accounts.' I decide to do something else and hit the home button. I come back later and finish importing.

### Actual behavior
K9 crashes when you hit the home button.

### Steps to reproduce
1. Open K9 on older phone (tested on API 15)
2. Click 'Import Settings and Accounts'
3. Press home button

### Environment
K-9 Mail version: [Most recent](https://github.com/k9mail/k-9/commit/d6090c626b3c136ea0a6a76279f954ac5d6dedb9) as of today

Android version: Nexus 5x API 15

Account type (IMAP, POP3, WebDAV/Exchange): N/A

Note: I also tested this on a recent phone (Nexus 5x API 26) and it worked fine, so it's not something we're doing directly.

Logs:

    11-13 14:26:43.401 20678-20678/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   android.app.SuperNotCalledException: Activity {android/com.android.internal.app.ChooserActivity} did not call through to super.onStop()
                                                                       at android.app.Activity.performStop(Activity.java:4606)
                                                                       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3071)
                                                                       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3130)
                                                                       at android.app.ActivityThread.access$1200(ActivityThread.java:123)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1180)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:4424)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                                                                       at dalvik.system.NativeStart.main(Native Method)

Other (possibly related?) warning:

    11-13 14:26:37.301 20678-20678/com.fsck.k9.debug W/dalvikvm: VFY: unable to resolve virtual method 1406: Landroid/os/PowerManager;.isIgnoringBatteryOptimizations (Ljava/lang/String;)Z

**Comment by jyn514** [comment]
I don't know if this is related - apparently the Nexus 5x VM doesn't come with a file browser by default? I'm searching through the options now, but it seems strange things are going on.

**Comment by jyn514** [comment]
So I deleted the entire virtual image and made a new one, and it's now constantly throwing errors for any and everything (for at least 15 minutes). I don't think this is related to K9? I'm going to use a different phone VM and see if that helps at all.
