### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#2938]
### Expected behavior
socket connect succeed

### Actual behavior
socket connect failed

### Steps to reproduce
1.to refresh mail list
2.see logcat

this is log :
11-15 14:30:43.184 29209-29234/? W/k9: Could not connect to imap.exmail.qq.com/14.17.57.217
                                       java.net.SocketException: SOCKS connection failed
                                           at java.net.PlainSocketImpl.socksConnect(PlainSocketImpl.java:323)
                                           at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:181)
                                           at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
                                           at java.net.Socket.connect(Socket.java:882)
                                           at com.fsck.k9.mail.ssl.DefaultTrustedSocketFactory.createSocket(DefaultTrustedSocketFactory.java:178)
                                           at com.fsck.k9.mail.store.imap.ImapConnection.connectToAddress(ImapConnection.java:207)
                                           at com.fsck.k9.mail.store.imap.ImapConnection.connect(ImapConnection.java:182)
                                           at com.fsck.k9.mail.store.imap.ImapConnection.open(ImapConnection.java:106)
                                           at com.fsck.k9.mail.store.imap.ImapConnection.sendCommand(ImapConnection.java:630)
                                           at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:613)
                                           at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:602)
                                           at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
                                           at com.fsck.k9.mail.store.imap.ImapFolder.internalOpen(ImapFolder.java:145)
                                           at com.fsck.k9.mail.store.imap.ImapFolder.open(ImapFolder.java:114)
                                           at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:862)
                                           at com.fsck.k9.controller.MessagingController.access$300(MessagingController.java:100)
                                           at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:755)
                                           at com.fsck.k9.controller.MessagingController.run(MessagingController.java:258)

### Environment
K-9 Mail version:

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment]
This is most likely a network issue, not a bug in the app. Also, information about the environment is missing.
