### ISSUE TITLE
K-9 crash (messageview.MessageViewFragment.removeDialog)

### ISSUE THREAD

**Issue by Massedil** [k9mail/k-9#3099]
I was downloading an email attachment in background and k9 hasn't arrived to connect to internet (as often).

Log is here :

```
01-15 18:35:09.548 I/ActivityManager(3046): Killing 4302:com.fsck.k9/u0a83 (adj 906): empty for 1803s
01-15 18:47:59.562 I/ActivityManager(3046): Start proc 28856:com.fsck.k9/u0a83 for broadcast com.fsck.k9/.service.BootReceiver
01-15 18:48:18.995 I/ActivityManager(3046): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.Accounts bnds=[164,1134][298,1286] (has extras)} from uid 10028 on display 0
01-15 18:48:20.274 I/ActivityManager(3046): START u0 {flg=0x14000000 cmp=com.fsck.k9/.activity.MessageList (has extras)} from uid 10083 on display 0
01-15 18:48:45.007 I/WindowManager(3046): Screen frozen for +1s166ms due to Window{88829a5 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
01-15 19:15:25.351 I/ActivityManager(3046): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.Accounts bnds=[164,1134][298,1286] (has extras)} from uid 10028 on display 0
01-15 19:16:41.823 E/AndroidRuntime(28856): Process: com.fsck.k9, PID: 28856
01-15 19:16:41.823 E/AndroidRuntime(28856): at com.fsck.k9.ui.messageview.MessageViewFragment.removeDialog(MessageViewFragment.java:569)
01-15 19:16:41.823 E/AndroidRuntime(28856): at com.fsck.k9.ui.messageview.MessageViewFragment.access$200(MessageViewFragment.java:57)
01-15 19:16:41.823 E/AndroidRuntime(28856): at com.fsck.k9.ui.messageview.MessageViewFragment$3.run(MessageViewFragment.java:666)
01-15 19:16:42.614 W/ActivityManager(3046): Force finishing activity com.fsck.k9/.activity.MessageList
01-15 19:16:42.620 W/ActivityManager(3046): Force finishing activity com.fsck.k9/.activity.Accounts
01-15 19:16:42.626 I/ActivityManager(3046): Killing 28856:com.fsck.k9/u0a83 (adj 900): crash
01-15 19:16:47.217 I/ActivityManager(3046): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.Accounts bnds=[164,1134][298,1286] (has extras)} from uid 10028 on display 0
01-15 19:16:47.283 I/ActivityManager(3046): Start proc 30727:com.fsck.k9/u0a83 for activity com.fsck.k9/.activity.Accounts
01-15 19:16:47.934 I/ActivityManager(3046): Displayed com.fsck.k9/.activity.Accounts: +695ms
```

### Environment
K-9 Mail version: 5.402 F-droid

Android version: 7.1.2 (LOS)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
This is also missing the line containing the exception type and message.

**Comment by Massedil** [comment]
It's also the first time for me this crash happens and I have no more log about that today. If it occurs again I will try to capture more logs.

**Comment by cketti** [comment]
Feel free to open a new issue then.
