### ISSUE TITLE
K-9 crash (EmailProviderCacheCursor.moveToPosition)

### ISSUE THREAD

**Issue by Massedil** [k9mail/k-9#3100]
With Android option "background sync" activated today.

Here is the log :

```

01-16 10:21:54.786 I/ActivityManager(3016): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.Accounts bnds=[164,1134][298,1286] (has extras)} from uid 10028 on display 0
01-16 10:21:56.273 I/ActivityManager(3016): START u0 {flg=0x14000000 cmp=com.fsck.k9/.activity.MessageList (has extras)} from uid 10083 on display 0
01-16 10:22:18.440 I/ActivityManager(3016): START u0 {act=com.fsck.k9.intent.action.REPLY cmp=com.fsck.k9/.activity.MessageCompose (has extras)} from uid 10083 on display 0
01-16 12:25:24.207 I/ActivityManager(3016): Waited long enough for: ServiceRecord{af8ea32 u0 com.fsck.k9/.service.PushService}
01-16 12:25:24.227 I/ActivityManager(3016): Waited long enough for: ServiceRecord{8032383 u0 com.fsck.k9/.service.PollService}
01-16 12:36:40.652 I/ActivityManager(3016): Waited long enough for: ServiceRecord{8eaf4f1 u0 com.fsck.k9/.service.PollService}
01-16 12:49:24.731 I/ActivityManager(3016): Waited long enough for: ServiceRecord{7018e7d u0 com.fsck.k9/.service.PollService}
01-16 13:04:31.831 I/ActivityManager(3016): Waited long enough for: ServiceRecord{ec6a208 u0 com.fsck.k9/.service.PollService}
01-16 13:19:37.166 I/ActivityManager(3016): Waited long enough for: ServiceRecord{f214b4b u0 com.fsck.k9/.service.PollService}
01-16 13:36:24.946 I/ActivityManager(3016): Waited long enough for: ServiceRecord{3d4bab6 u0 com.fsck.k9/.service.PollService}
01-16 13:50:32.597 I/ActivityManager(3016): Waited long enough for: ServiceRecord{4777bfb u0 com.fsck.k9/.service.PollService}
01-16 14:04:34.836 I/ActivityManager(3016): Waited long enough for: ServiceRecord{9d88be5 u0 com.fsck.k9/.service.PollService}
01-16 14:20:50.559 I/ActivityManager(3016): Waited long enough for: ServiceRecord{69148ee u0 com.fsck.k9/.service.PollService}
01-16 14:36:47.972 I/ActivityManager(3016): Waited long enough for: ServiceRecord{63f3d9c u0 com.fsck.k9/.service.PollService}
01-16 14:49:11.821 I/ActivityManager(3016): Waited long enough for: ServiceRecord{665d68b u0 com.fsck.k9/.service.PollService}
01-16 15:04:19.585 I/ActivityManager(3016): Waited long enough for: ServiceRecord{4fe60d1 u0 com.fsck.k9/.service.PollService}
01-16 15:21:48.822 I/ActivityManager(3016): Waited long enough for: ServiceRecord{6422c5c u0 com.fsck.k9/.service.PollService}
01-16 15:36:54.915 I/ActivityManager(3016): Waited long enough for: ServiceRecord{ed10050 u0 com.fsck.k9/.service.PollService}
01-16 15:52:01.593 I/ActivityManager(3016): Waited long enough for: ServiceRecord{33469cf u0 com.fsck.k9/.service.PollService}
01-16 16:03:27.636 I/ActivityManager(3016): Waited long enough for: ServiceRecord{7abf5be u0 com.fsck.k9/.service.PollService}
01-16 16:17:14.911 I/ActivityManager(3016): Waited long enough for: ServiceRecord{c03eca3 u0 com.fsck.k9/.service.PollService}
01-16 16:29:37.552 I/ActivityManager(3016): Waited long enough for: ServiceRecord{652c1ea u0 com.fsck.k9/.service.PollService}
01-16 16:41:14.941 I/ActivityManager(3016): Waited long enough for: ServiceRecord{dcbe09e u0 com.fsck.k9/.service.PollService}
01-16 16:53:42.834 I/ActivityManager(3016): Waited long enough for: ServiceRecord{f1be1c2 u0 com.fsck.k9/.service.PollService}
01-16 17:05:15.576 I/ActivityManager(3016): Waited long enough for: ServiceRecord{3a10c1 u0 com.fsck.k9/.service.PollService}
01-16 17:17:40.234 I/ActivityManager(3016): Waited long enough for: ServiceRecord{7fd6b2e u0 com.fsck.k9/.service.PollService}
01-16 17:48:17.645 I/ActivityManager(3016): Waited long enough for: ServiceRecord{6fab4c5 u0 com.fsck.k9/.service.PollService}
01-16 18:03:23.042 I/ActivityManager(3016): Waited long enough for: ServiceRecord{e089c00 u0 com.fsck.k9/.service.PollService}
01-16 18:19:48.059 I/ActivityManager(3016): Waited long enough for: ServiceRecord{6d2a2f6 u0 com.fsck.k9/.service.PollService}
01-16 18:20:22.390 I/ActivityManager(3016): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.Accounts bnds=[164,1134][298,1286] (has extras)} from uid 10028 on display 0
01-16 18:20:27.044 E/AndroidRuntime(6429): Process: com.fsck.k9, PID: 6429
01-16 18:20:27.044 E/AndroidRuntime(6429): at com.fsck.k9.cache.EmailProviderCacheCursor.moveToPosition(EmailProviderCacheCursor.java:112)
01-16 18:20:27.044 E/AndroidRuntime(6429): at com.fsck.k9.fragment.MessageListFragment.setActiveMessage(MessageListFragment.java:2874)
01-16 18:20:27.044 E/AndroidRuntime(6429): at com.fsck.k9.activity.MessageList.showMessageList(MessageList.java:1531)
01-16 18:20:27.044 E/AndroidRuntime(6429): at com.fsck.k9.activity.MessageList.goBack(MessageList.java:1421)
01-16 18:20:27.044 E/AndroidRuntime(6429): at com.fsck.k9.fragment.MessageListHandler.handleMessage(MessageListHandler.java:128)
01-16 18:20:27.047 W/ActivityManager(3016): Force finishing activity com.fsck.k9/.activity.MessageList
01-16 18:20:27.552 W/ActivityManager(3016): Activity pause timeout for ActivityRecord{750843a u0 com.fsck.k9/.activity.MessageList t16622 f}
01-16 18:20:30.868 I/ActivityManager(3016): Killing 6429:com.fsck.k9/u0a83 (adj 0): crash
01-16 18:20:30.877 W/ActivityManager(3016): Scheduling restart of crashed service com.fsck.k9/.service.PollService in 1000ms
01-16 18:20:30.927 I/ActivityManager(3016): Start proc 23136:com.fsck.k9/u0a83 for activity com.fsck.k9/.activity.Accounts
01-16 18:20:31.155 W/InputDispatcher(3016): channel 'fc901a9 com.fsck.k9/com.fsck.k9.activity.Accounts (server)' ~ Consumer closed input channel or an error occurred. events=0x9
01-16 18:20:31.155 E/InputDispatcher(3016): channel 'fc901a9 com.fsck.k9/com.fsck.k9.activity.Accounts (server)' ~ Channel is unrecoverably broken and will be disposed!
01-16 18:20:31.160 W/InputDispatcher(3016): channel 'c20c61d com.fsck.k9/com.fsck.k9.activity.MessageList (server)' ~ Consumer closed input channel or an error occurred. events=0x9
01-16 18:20:31.160 E/InputDispatcher(3016): channel 'c20c61d com.fsck.k9/com.fsck.k9.activity.MessageList (server)' ~ Channel is unrecoverably broken and will be disposed!
01-16 18:20:31.161 W/InputDispatcher(3016): channel 'e907d6a com.fsck.k9/com.fsck.k9.activity.MessageCompose (server)' ~ Consumer closed input channel or an error occurred. events=0x9
01-16 18:20:31.161 E/InputDispatcher(3016): channel 'e907d6a com.fsck.k9/com.fsck.k9.activity.MessageCompose (server)' ~ Channel is unrecoverably broken and will be disposed!
01-16 18:20:31.163 I/WindowManager(3016): WIN DEATH: Window{fc901a9 u0 com.fsck.k9/com.fsck.k9.activity.Accounts}
01-16 18:20:31.163 W/InputDispatcher(3016): Attempted to unregister already unregistered input channel 'fc901a9 com.fsck.k9/com.fsck.k9.activity.Accounts (server)'
01-16 18:20:31.166 I/WindowManager(3016): WIN DEATH: Window{e907d6a u0 com.fsck.k9/com.fsck.k9.activity.MessageCompose}
01-16 18:20:31.166 W/InputDispatcher(3016): Attempted to unregister already unregistered input channel 'e907d6a com.fsck.k9/com.fsck.k9.activity.MessageCompose (server)'
01-16 18:20:31.169 I/WindowManager(3016): WIN DEATH: Window{c20c61d u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
01-16 18:20:31.169 W/InputDispatcher(3016): Attempted to unregister already unregistered input channel 'c20c61d com.fsck.k9/com.fsck.k9.activity.MessageList (server)'
01-16 18:20:31.751 I/ActivityManager(3016): Displayed com.fsck.k9/.activity.Accounts: +863ms

```
### Environment
K-9 Mail version: 5.402 F-droid

Android version: 7.1.2 (LOS)

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment]
That log seems to be incomplete. It's missing the line containing the exception type and message.

**Comment by Massedil** [comment]
It's the first time for me this crash happens and I have no more log about that today. If it occurs again I will try to capture more logs.

**Comment by cketti** [comment]
Feel free to open a new issue then.
