### ISSUE TITLE
Crash when opening if inbox was never synchronized

### ISSUE THREAD

**Issue by wiktor-k** [k9mail/k-9#3455]
### Expected behavior
The app should show folders on startup.

### Actual behavior
K9 crashes on startup

### Steps to reproduce
1. Install clean application from master,
2. Setup account with dummy data so it never connects to the server
3. Finish the setup wizard
4. Stop the app and start it again

### Environment
K-9 Mail version:04ec7227f292716d1fcb0dabe19a1e311b24582d

Android version:Oreo

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

Stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.fsck.k9.debug, PID: 4121
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9.debug/com.fsck.k9.activity.MessageList}: java.lang.RuntimeException: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: INBOX (-1)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6940)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.RuntimeException: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: INBOX (-1)
    at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:643)
    at com.fsck.k9.fragment.MessageListFragment.decodeArguments(MessageListFragment.java:581)
    at com.fsck.k9.fragment.MessageListFragment.onCreate(MessageListFragment.java:434)
    at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
    at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
    at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
    at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
    at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340)
    at android.app.Activity.performStart(Activity.java:7191)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
    at android.app.ActivityThread.-wrap11(Unknown Source:0) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
    at android.os.Handler.dispatchMessage(Handler.java:105) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.app.ActivityThread.main(ActivityThread.java:6940) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
Caused by: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: INBOX (-1)
    at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:172)
    at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:151)
    at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:274)
    at com.fsck.k9.mailstore.LocalFolder.open(LocalFolder.java:151)
    at com.fsck.k9.fragment.MlfUtils.getOpenFolder(MlfUtils.java:27)
    at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:640)
    at com.fsck.k9.fragment.MessageListFragment.decodeArguments(MessageListFragment.java:581) 
    at com.fsck.k9.fragment.MessageListFragment.onCreate(MessageListFragment.java:434) 
    at android.support.v4.app.Fragment.performCreate(Fragment.java:2331) 
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386) 
    at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188) 
    at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071) 
    at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115) 
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380) 
    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338) 
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245) 
    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248) 
    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200) 
    at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195) 
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597) 
    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177) 
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1340) 
    at android.app.Activity.performStart(Activity.java:7191) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2920) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
    at android.app.ActivityThread.-wrap11(Unknown Source:0) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
    at android.os.Handler.dispatchMessage(Handler.java:105) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.app.ActivityThread.main(ActivityThread.java:6940) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
Application terminated.
```

**Comment by cketti** [comment]
Should be fixed in current `master`.

**Comment by wiktor-k** [comment]
Thanks!
