### ISSUE TITLE
Search crashes the app

### ISSUE THREAD

**Issue by wiktor-k** [k9mail/k-9#3716]
### Expected behavior
Search should work.

### Actual behavior
Entering any query in the search box (e.g. "f") and pressing search button crashes the application.

### Steps to reproduce
1. Open the app
2. Click search magnifying icon
3. Type "f" and press Enter

### Environment
K-9 Mail version: bb87dcc931283ca54d891e519a7ffcabafe246bd (master branch)

Android version: 8.0

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

Crash log:
```
11-16 13:50:25.092 11435 11435 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9.debug/com.fsck.k9.activity.Search}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.fsck.k9.ui.K9Drawer.selectFolder(java.lang.String)' on a null object reference
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6940)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.fsck.k9.ui.K9Drawer.selectFolder(java.lang.String)' on a null object reference
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at com.fsck.k9.activity.MessageList.initializeFromLocalSearch(MessageList.java:1702)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at com.fsck.k9.activity.MessageList.decodeExtras(MessageList.java:498)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at com.fsck.k9.activity.MessageList.onCreate(MessageList.java:244)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7183)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
11-16 13:50:25.092 11435 11435 E AndroidRuntime: 	... 9 more
```

**Comment by morckx** [comment]
Does [this](https://github.com/morckx/k-9/commit/184cdb542927e32333b7abcc900c16cd29359d18) fix the crash and #3717?

It is, however, rather a workaround, for now.

**Comment by morckx** [comment]
Haha, your issue #3718 just reminded me that I had my buttons re-ordered so that the reply-button is always visible, but I can't find my commit anymore.
Apart from that (and that K9MAIL_INTERNAL_OUTBOX is not created automatically on settings imports) master runs OK for me.

**Comment by wiktor-k** [comment]
> master runs OK for me.

Do you mean your master or k-9/master?

I see your fork has diverged a little:

> This branch is 24 commits ahead, 95 commits behind k9mail:master. 

But I'd be interested in looking at the changes you have that k9 doesn't (maybe the reordering commit is there :) ).

Thanks for your time!

**Comment by morckx** [comment]
I mean k9/master. My master branch and everything except bughunt is outdated. I think, I'm on my bughunt branch and, unfortunately, the reply menu is only visible in landscape mode.

**Comment by wiktor-k** [comment]
Okay, from my today's bisecting it seems that commit d6daea3c1278c689c3278f3b12b8bbc1b73b1861 introduced this bug. And this commit is not in your bughunt branch:

    git merge-base --is-ancestor remotes/morckx/bughunt d6daea3c1278c689c3278f3b12b8bbc1b73b1861; echo $?

That's why you don't see it (by the way nice date dividers in bughunt, they look really cool!).

I'll see what I can do about this...

**Comment by wiktor-k** [comment]
Hmm... weird, now I can't reproduce the search bug when [your patch](https://github.com/morckx/k-9/commit/184cdb542927e32333b7abcc900c16cd29359d18) is applied on top of k9/master @morckx. Is there a reason you didn't submit this one as a PR? It obviously makes things better and is quite minimal...

**Comment by morckx** [comment]
I had only some minor reasons: 

- It's no proper fix, but rather a workaround. For a real fix we would probably have to have two flags "the drawer is option is enabled" and "the drawer is initialized". I intended to provide a proper fix later, but had no time.
- the drawer still seems to be wip, anyway
