### ISSUE TITLE
  java.io.IOException: Expected 000a (     ) but got 0064 (d)

### ISSUE THREAD

**Issue by zhangxiaofan918** [k9mail/k-9#3780]
java.io.IOException: Expected 000a (
    ) but got 0064 (d)
        at com.minxing.kit.mail.k9.mail.store.ImapResponseParser.expect(ImapResponseParser.java:366)
        at com.minxing.kit.mail.k9.mail.store.ImapResponseParser.parseResponseText(ImapResponseParser.java:123)
        at com.minxing.kit.mail.k9.mail.store.ImapResponseParser.readTokens(ImapResponseParser.java:77)
        at com.minxing.kit.mail.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:53)
        at com.minxing.kit.mail.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:31)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2903)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:3056)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:3038)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapConnection.login(ImapStore.java:2802)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2644)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapConnection.sendCommand(ImapStore.java:3003)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:3052)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:3033)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:868)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:914)
        at com.minxing.kit.mail.k9.mail.store.ImapStore$ImapFolder.open(ImapStore.java:877)
        at com.minxing.kit.mail.k9.controller.MessagingController$19.run(MessagingController.java:3404)

### Actual behavior
I set a maximum value. When it is less than this value, the attachment will be downloaded automatically, so the above error occurs. What is the reason?

### Steps to reproduce
1. open message
2. the attachment download automatically
3. attachment is not automatically downloaded and print something wrong logcat above.

### Environment
K-9 Mail version: lastest version

Android version: Android 9.0

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by cketti** [comment]
Please only report bugs you can reproduce with the open source version. And make sure to include the hash of the Git commit so others are able to reproduce the issue.
