### ISSUE TITLE
Notification settings crash

### ISSUE THREAD

**Issue by ByteHamster** [k9mail/k-9#3782]
I am using Android 8.1, built from master. Crash when clicking all account settings menu items EXCEPT the notifications screen. Pretty sure this is caused by #3761 from @wiktor-k.

```
12-02 17:16:48.234 12067-12067/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 12067
    java.lang.IllegalStateException: findPreference(it) must not be null
        at com.fsck.k9.ui.settings.account.AccountSettingsFragment.initializeNotifications(AccountSettingsFragment.kt:169)
        at com.fsck.k9.ui.settings.account.AccountSettingsFragment.onCreatePreferencesFix(AccountSettingsFragment.kt:69)
        at com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:62)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-02 17:16:48.241 2247-15996/? W/ActivityManager:   Force finishing activity com.fsck.k9.debug/com.fsck.k9.ui.settings.account.AccountSettingsActivity
12-02 17:16:48.251 2247-2344/? I/ActivityManager: Showing crash dialog for package com.fsck.k9.debug u0
```

**Comment by wiktor-k** [comment]
Yes, sounds like it, sorry! I'll fix it ASAP!
