### ISSUE TITLE
Android Studio deployment fails with instant build (docs update)

### ISSUE THREAD

**Issue by pfaucon** [k9mail/k-9#3963]
### Expected behavior
When building the app should be able to deploy

### Actual behavior
Android studio defaults to allowing instant apps, which crash instantly

### Steps to reproduce
1. enable instant apps (or don't disable them after installing/updating Android Studio)
2. try to run the app

### Suggested resolution
I'm not familiar with instant apps, but perhaps mentioning the requirement in the readme would be sufficient (luckily many other projects have the same issue so searching github lead to a quick resolution), else maybe modifying the config to include the required libraries

### Environment
K-9 Mail version: Master branch

Android version: API 28 simulator Android Studio 3.3.2

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

![image](https://user-images.githubusercontent.com/3473919/54162566-1f32c880-4413-11e9-83a6-9098eed3e2f1.png)

```
03/11 15:35:14: Launching k9mail
$ adb shell am start -n "com.fsck.k9.debug/com.fsck.k9.activity.Accounts" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: com.fsck.k9.tests | com.fsck.k9.debug
Waiting for application to come online: com.fsck.k9.tests | com.fsck.k9.debug
Waiting for application to come online: com.fsck.k9.tests | com.fsck.k9.debug
Waiting for application to come online: com.fsck.k9.tests | com.fsck.k9.debug
Waiting for application to come online: com.fsck.k9.tests | com.fsck.k9.debug
Connecting to com.fsck.k9.debug
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/m.fsck.k9.debu: Not late-enabling -Xcheck:jni (already on)
W/m.fsck.k9.debu: Unexpected CPU variant for X86 using defaults: x86
W/ActivityThread: Application com.fsck.k9.debug is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8601', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/chatty: uid=10087(com.fsck.k9.debug) identical 3 lines
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1337)
I/m.fsck.k9.debu: The ClassLoaderContext is a special shared library.
W/m.fsck.k9.debu: JIT profile information will not be recorded: profile file does not exits.
W/m.fsck.k9.debu: JIT profile information will not be recorded: profile file does not exits.
I/InstantRun: starting instant run server: is main process
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 5563
    java.lang.RuntimeException: Unable to get provider androidx.lifecycle.ProcessLifecycleOwnerInitializer: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ProcessLifecycleOwnerInitializer" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/base.apk", zip file "/data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/split_lib_resources_apk.apk", zip file "/data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/split_lib_slice_0_apk.apk"],nativeLibraryDirectories=[/data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/lib/x86, /system/fake-libs, /data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/base.apk!/lib/x86, /data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/split_lib_slice_0_apk.apk!/lib/x86, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ProcessLifecycleOwnerInitializer" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/base.apk", zip file "/data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/split_lib_resources_apk.apk", zip file "/data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/split_lib_slice_0_apk.apk"],nativeLibraryDirectories=[/data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/lib/x86, /system/fake-libs, /data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/base.apk!/lib/x86, /data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/split_lib_slice_0_apk.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:62)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6380)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.fsck.k9.debug-rhIuK0M1gthQNytlgRjtpg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
E/AndroidRuntime:     at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        		... 8 more```

**Comment by cketti** [comment]
Please note that [Instant Run](https://developer.android.com/studio/run#instant-run) and [Instant Apps](https://developer.android.com/topic/google-play-instant) are different things.

Because of multiple issues Instant Run will be removed from future versions of Android Studio. So this will probably not be a problem for much longer. 
But please feel free to add to K-9 Mail's build instructions: https://github.com/k9mail/k-9/wiki/BuildingK9
