### ISSUE TITLE
K-9 is crashing indefinitely. Env: Android Q beta 3 (Google Pixel phone)

### ISSUE THREAD

**Issue by skmobeen** [k9mail/k-9#4047]
K-9 is crashing indefinitely on Android Q beta (Google Pixel phone). Please update the app. Sorry, couldn't pull the logs. App doesn't launch at all to get the PID.
Thank you!

### Environment
K-9 Mail version: 5.600

Android version:
Android Q beta 3 Build# QPP3.190404.015 Kernel version 3.18.137-gc7efb62b8e5b

**Comment by cketti** [comment]
See #4042.

Without a log there's no telling what is happening exactly.

**Comment by cketti** [comment]
If you can't get the PID, you can still record an unfiltered log and remove unrelated/privacy-relevant log statements by hand.

**Comment by njeyaakili** [comment]
if you uninstall and reinstall k9 it works fine with q beta-3 (on an essential ph-1). obviously not the ideal solution, but a workaround.

**Comment by skmobeen** [comment]
> if you uninstall and reinstall k9 it works fine with q beta-3 (on an essential ph-1). obviously not the ideal solution, but a workaround.

Thank you very much @njeyaakili. That worked. My bad, I should have tried this before posting an issue.

**Comment by xf-** [comment]
@cketti  Won't help. Looks like the WebView beta crashes the app.

```
E WebViewFactory: Chromium WebView package does not exist
E WebViewFactory: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
E WebViewFactory:        at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:339)
E WebViewFactory:        at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
E WebViewFactory:        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
E WebViewFactory:        at android.webkit.WebView.getFactory(WebView.java:2546)
E WebViewFactory:        at android.webkit.WebView.ensureProviderCreated(WebView.java:2540)
E WebViewFactory:        at android.webkit.WebView.setOverScrollMode(WebView.java:2608)
E WebViewFactory:        at android.view.View.<init>(View.java:5172)
E WebViewFactory:        at android.view.View.<init>(View.java:5311)
E WebViewFactory:        at android.view.ViewGroup.<init>(ViewGroup.java:675)
E WebViewFactory:        at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
E WebViewFactory:        at android.webkit.WebView.<init>(WebView.java:410)
E WebViewFactory:        at android.webkit.WebView.<init>(WebView.java:353)
E WebViewFactory:        at android.webkit.WebView.<init>(WebView.java:336)
E WebViewFactory:        at android.webkit.WebView.<init>(WebView.java:323)
E WebViewFactory:        at android.webkit.WebView.<init>(WebView.java:313)
E WebViewFactory:        at de.cketti.library.changelog.ChangeLog.getDialog(ChangeLog.java:285)
E WebViewFactory:        at de.cketti.library.changelog.ChangeLog.getLogDialog(ChangeLog.java:263)
E WebViewFactory:        at com.fsck.k9.activity.MessageList.onCreate(MessageList.java:236)
E WebViewFactory:        at android.app.Activity.performCreate(Activity.java:7698)
E WebViewFactory:        at android.app.Activity.performCreate(Activity.java:7687)
E WebViewFactory:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
E WebViewFactory:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096)
E WebViewFactory:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
E WebViewFactory:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
E WebViewFactory:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E WebViewFactory:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E WebViewFactory:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1935)
E WebViewFactory:        at android.os.Handler.dispatchMessage(Handler.java:107)
E WebViewFactory:        at android.os.Looper.loop(Looper.java:214)
E WebViewFactory:        at android.app.ActivityThread.main(ActivityThread.java:7116)
E WebViewFactory:        at java.lang.reflect.Method.invoke(Native Method)
E WebViewFactory:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E WebViewFactory:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
D AndroidRuntime: Shutting down VM
```

**Comment by nailyk-fr** [comment]
Hello. 

Just switched my device to Pie and get that exact crash. 
Is there any solution ? 

(already tried to reinstall the app without luck)
Is it an app problem or a rom problem? (I am building omninrom Pie)
[k9.txt](https://github.com/k9mail/k-9/files/3374362/k9.txt)

Thanks in advance :)
