### ISSUE TITLE
Crash when starting without configured account

### ISSUE THREAD

**Issue by ByteHamster** [k9mail/k-9#4352]
I just tried to setup an empty instance of K9 in an emulator. When skipping the complete account setup, and then trying to open the app, it crashes. 

### Steps to reproduce
1. Set up K9 and enter random text instead of a real email account. Press skip on all screens.
2. Open app

### Environment
K-9 Mail version: 89128fbd62a17b5149b9914818c98d042d12f005

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

```
2019-12-09 23:22:18.434 8286-8286/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 8286
    java.lang.RuntimeException: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: INBOX (-1)
        at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:638)
        at com.fsck.k9.fragment.MessageListFragment.decodeArguments(MessageListFragment.java:553)
        at com.fsck.k9.fragment.MessageListFragment.onCreate(MessageListFragment.java:407)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at com.fsck.k9.activity.MessageList.onStart(MessageList.java:566)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: INBOX (-1)
        at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:186)
        at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:165)
        at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:273)
        at com.fsck.k9.mailstore.LocalFolder.open(LocalFolder.java:165)
        at com.fsck.k9.fragment.MlfUtils.getOpenFolder(MlfUtils.java:29)
        at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:635)
        at com.fsck.k9.fragment.MessageListFragment.decodeArguments(MessageListFragment.java:553) 
        at com.fsck.k9.fragment.MessageListFragment.onCreate(MessageListFragment.java:407) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838) 
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197) 
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080) 
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613) 
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201) 
        at com.fsck.k9.activity.MessageList.onStart(MessageList.java:566) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391) 
        at android.app.Activity.performStart(Activity.java:7157) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by JohnScott623** [comment]
I have been using KMail 5.7 for about a week, but now it crashes immediately when I try to open it with a very similar log:
````
--------- beginning of main
12-16 12:58:58.394  2518  2518 E com.fsck.k9: Not starting debugger since process cannot load the jdwp agent.
12-16 12:58:58.544  2518  2518 D NetworkSecurityConfig: No Network Security Config specified, using platform default
12-16 12:58:58.729  2518  2518 I WebViewFactory: Loading com.android.chrome version 79.0.3945.79 (code 394507937)
12-16 12:58:58.772  2518  2518 I cr_LibraryLoader: Time to load native libraries: 2 ms
12-16 12:58:58.791  2518  2518 I chromium: [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
12-16 12:58:58.792  2518  2518 I cr_LibraryLoader: Expected native library version number "79.0.3945.79", actual native library version number "79.0.3945.79"
12-16 12:58:58.800  2518  2581 W cr_ChildProcLH: Create a new ChildConnectionAllocator with package name = com.android.chrome, sandboxed = true
12-16 12:58:58.802  2518  2518 I cr_BrowserStartup: Initializing chromium process, singleProcess=false
12-16 12:58:58.903  2518  2607 W cr_media: Requires BLUETOOTH permission
12-16 12:58:58.906  2518  2648 I Adreno  : QUALCOMM build                   : 94a5458, I21281c58c8
12-16 12:58:58.906  2518  2648 I Adreno  : Build Date                       : 12/18/18
12-16 12:58:58.906  2518  2648 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.03.02
12-16 12:58:58.906  2518  2648 I Adreno  : Local Branch                     : 
12-16 12:58:58.906  2518  2648 I Adreno  : Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.6.2.R1.09.00.00.463.046
12-16 12:58:58.906  2518  2648 I Adreno  : Remote Branch                    : NONE
12-16 12:58:58.906  2518  2648 I Adreno  : Reconstruct Branch               : NOTHING
12-16 12:58:58.906  2518  2648 I Adreno  : Build Config                     : S L 6.0.7 AArch64
12-16 12:58:58.909  2518  2648 I Adreno  : PFP: 0x005ff112, ME: 0x005ff066
12-16 12:58:58.914  2518  2648 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
12-16 12:58:58.914  2518  2648 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
12-16 12:58:58.922  2518  2518 D OpenGLRenderer: Skia GL Pipeline
12-16 12:58:58.969  2518  2518 D AndroidRuntime: Shutting down VM
--------- beginning of crash
12-16 12:58:58.970  2518  2518 E AndroidRuntime: FATAL EXCEPTION: main
12-16 12:58:58.970  2518  2518 E AndroidRuntime: Process: com.fsck.k9, PID: 2518
12-16 12:58:58.970  2518  2518 E AndroidRuntime: java.lang.RuntimeException: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: INBOX (-1)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:638)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.decodeArguments(MessageListFragment.java:553)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onCreate(MessageListFragment.java:407)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.activity.MessageList.onStart(MessageList.java:566)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1413)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7169)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3146)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6923)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
12-16 12:58:58.970  2518  2518 E AndroidRuntime: Caused by: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: INBOX (-1)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:186)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:165)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:273)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.mailstore.LocalFolder.open(LocalFolder.java:165)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.fragment.MlfUtils.getOpenFolder(MlfUtils.java:29)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:635)
12-16 12:58:58.970  2518  2518 E AndroidRuntime:        ... 30 more
12-16 12:58:58.970  2518  2648 W VideoCapabilities: Unrecognized profile 4 for video/hevc
12-16 12:58:58.972  2518  2648 W VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
12-16 12:58:59.005  2518  2648 I VideoCapabilities: Unsupported profile 4 for video/mp4v-es
````

**Comment by danthe93** [comment]
I am experiencing this issue as well.

**Comment by cketti** [comment]
Should be the same underlying bug as #3691.
