### ISSUE TITLE
unable to change the account

### ISSUE THREAD

**Issue by mpas97** [k9mail/k-9#4558]
### Actual behavior
The app crashes when I want to change to any other account.

### Steps to reproduce
1. Open app
2. Open navigation drawer
3. Click on a different mail account / unified inbox

### Environment
K-9 Mail version: 5.706 (706b13b)

Android version: 9

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 4268
    android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.fsck.k9.search.ConditionsTreeNode
        at android.os.Parcel.readParcelableCreator(Parcel.java:2849)
        at android.os.Parcel.readParcelable(Parcel.java:2771)
        at com.fsck.k9.search.LocalSearch.<init>(LocalSearch.java:393)
        at com.fsck.k9.search.LocalSearch$1.createFromParcel(LocalSearch.java:378)
        at com.fsck.k9.search.LocalSearch$1.createFromParcel(LocalSearch.java:374)
        at com.fsck.k9.helper.ParcelableUtil.unmarshall(ParcelableUtil.java:20)
        at com.fsck.k9.activity.MessageList.decodeExtras(MessageList.java:476)
        at com.fsck.k9.activity.MessageList.onNewIntent(MessageList.java:297)
        at android.app.Activity.performNewIntent(Activity.java:7471)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1387)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1399)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3685)
        at android.app.ActivityThread.performNewIntents(ActivityThread.java:3701)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3718)
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by cketti** [comment]
Works for me.

If I had to guess, I'd say d8 is stripping the `CREATOR` field from `ConditionsTreeNode`. I had something like this happen once because the build tools wouldn't include `proguard-android.txt` which contains keep rules for Parcelable stuff. 
I can't remember how I fixed it in the end. I believe it involved cleaning all of the caches I could find.

**Comment by mpas97** [comment]
Thanks for this hint, so I just deleted .gradle and build folders and it directly worked again 👍
