### ISSUE TITLE
Moving message to folder renamed on server causes "Folder not found" exception and failure to sync changes

### ISSUE THREAD

**Issue by unode** [k9mail/k-9#4582]
### Expected behavior
I've been using the beta release on GooglePlay for quite some time without major issues.

### Actual behavior
Recently changes performed on k9-mail are no longer synchronized with the server.
I first noticed this after trying to move a message to a folder that had been renamed on another client. k9mail still displayed the folder with its old name. After moving the message to this "no longer existing folder" the message disappeared from inbox but didn't appear anywhere.
From this point onward actions performed by other clients are visible and new messages still appear but changing the read status (read/unread) has no effect and messages deleted in k9mail disappear from the k9 interface but remain on the server (visible in other clients).
I can't find a way to undo the initial move action or somehow make it fail to recover normal behavior.

In the logs I see:
```
03-03 15:35:28.365 27407 27423 D CommandMoveOrCopyMessag: processingPendingMoveOrCopy: source folder = INBOX, 1 messages, destination folder = folder_2020, isCopy = false
(...)
03-03 15:35:28.444 27407 27423 I ImapFolder: ImapFolder.copyMessages: couldn't find remote folder '"INBOX.folder_2020"' for SRV:INBOX/MessagingController/conn39734175
03-03 15:35:28.444 27407 27423 E MessagingController: Could not process command 'com.fsck.k9.controller.MessagingControllerCommands$PendingMoveOrCopy@7858ac1'
```
which is the folder that I tried to move a file to but was renamed before.

### Steps to reproduce
I'm not entirely sure the moved message caused the above behavior but it started happening after this. As such the steps to reproduce:
1. Create a folder on the server (IMAP protocol)
2. Refresh k9mail folder list, ensure the folder (`test`) is present in the list
3. On another client (webmail, etc...) rename the folder from `test` to `testing`.
4. In k9mail don't refresh the folder list and move a message to `test` - although the folder is now `testing` on the server, k9 still shows `test`.
5. Try toggling the read/unread status of a message and refresh the folder to force synchronization
6. Delete a message in k9 mail. Refresh the folder and check if the message was also deleted from the server (compare with other clients).

### Environment
K-9 Mail version: 5.705
Android version: 9
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

Following the error message above I also get:
```
03-03 15:35:28.444 27407 27423 E MessagingController: Could not process command 'com.fsck.k9.controller.MessagingControllerCommands$PendingMoveOrCopy@7858ac1'
03-03 15:35:28.444 27407 27423 E MessagingController: com.fsck.k9.mail.store.imap.FolderNotFoundException: Folder not found: folder_2020
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapFolder.copyMessages(ImapFolder.java:364)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapFolder.moveMessages(ImapFolder.java:383)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveOrCopyMessages(CommandMoveOrCopyMessages.java:74)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveMessages(CommandMoveOrCopyMessages.java:27)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.backend.imap.ImapBackend.moveMessages(ImapBackend.java:163)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:864)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:835)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingControllerCommands$PendingMoveOrCopy.execute(MessagingControllerCommands.java:71)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:704)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:603)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:597)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController$33.run(MessagingController.java:2466)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:220)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:113)
03-03 15:35:28.444 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
03-03 15:35:28.444 27407 27423 E MessagingController:   at java.lang.Thread.run(Thread.java:764)
03-03 15:35:28.445 27407 27423 E MessagingController: Failure processing command, but allow message sync attempt
03-03 15:35:28.445 27407 27423 E MessagingController: com.fsck.k9.mail.store.imap.FolderNotFoundException: Folder not found: folder_2020
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapFolder.copyMessages(ImapFolder.java:364)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.mail.store.imap.ImapFolder.moveMessages(ImapFolder.java:383)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveOrCopyMessages(CommandMoveOrCopyMessages.java:74)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.backend.imap.CommandMoveOrCopyMessages.moveMessages(CommandMoveOrCopyMessages.java:27)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.backend.imap.ImapBackend.moveMessages(ImapBackend.java:163)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:864)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:835)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingControllerCommands$PendingMoveOrCopy.execute(MessagingControllerCommands.java:71)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:704)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:603)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:597)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController$33.run(MessagingController.java:2466)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:220)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:113)
03-03 15:35:28.445 27407 27423 E MessagingController:   at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
03-03 15:35:28.445 27407 27423 E MessagingController:   at java.lang.Thread.run(Thread.java:764)
```

**Comment by unode** [comment]
As a workaround, is there any way to abort the pending move action or do I need to wait for a new beta release?

Thanks

**Comment by unode** [comment]
I have worked around this by exporting the account, removing it and re-importing.

**Comment by cketti** [comment]
This should no longer be an issue in recent beta versions.
