### ISSUE TITLE
Improve error reporting on send failures

### ISSUE THREAD

**Issue by cketti** [k9mail/k-9#4602]
We already save an error message when sending a message has failed (see `OutboxStateRepository`). Change the error notification to display that message and allow the user to either retry or move the message to the Drafts folder.

**Comment by dgtlmoon** [comment]
Small comments from #4594 in that "Send Again" actually means "Send a copy"

**Comment by stuart12** [comment]
"Send Again" on a message in the Outbox, appears to mean: make a copy, edit the copy and send the edited copy.

With k9 5.705, there appears to be a small bug in "Send Again". If you press it and then back out of the operation (discard the edit), k-9 drops you back into "Inbox" rather than leave you in "Outbox".

**Comment by EmanuelLoos** [comment]
What is the status on this? Changing this would not just be an enhancement but really solve a huge UI bug in my opinion. A user expects a software to retry something when specifically told to do so. A limit regarding manual retries makes no sense.

**Comment by abuesen** [comment]
Hi. 
Got "retries exceeded" on v6.716.

What is the actual state of this behaviour? 
Workaround availiable?

Couldn't find an answer in all linked issues.

regards, Andre.

**Comment by TheUnhappyUser2024** [comment]
I have version 6.804 and have the same issue where things randomly sit in outbox and refuse to send no matter how many times i push "send emails".
I have tried the trick of forwarding the email, but that still leaves the original email in the outbox.
I finally ended up copying all of the text and putting it into a new email which got sent right away. i then turned it into a draft and deleted it.
I have no idea where the logs mentioned above are, and i don't have time to go find them.
When is this problem going to be fixed? i am on a samsung sf20 with adroid version 13  and kernel version 4.19.113-27223811

**Comment by pboguslawski** [comment]
Similar problem in K-9 Mail 8.0 on Android 15. Two messages stuck in Outbox (probably after temp connection problems), manual resend throws notification with error description "Unable to send message". K-9 Mail logs:

```
11-06 08:57:51.975 13010 13028 I MessagingController: Running command 'sendPendingMessages', seq = 125 (background priority)
11-06 08:57:51.998 13010 13028 I MessagingController: Scanning Outbox folder for messages to send
11-06 08:57:51.999 13010 13028 V MessagingController: Skipping sending message K9LOCAL:a6c0c0f6-ef53-4c68-96bd-d3e4de3e02b0 (reason: error - Unable to send message)
11-06 08:57:52.000 13010 13028 V MessagingController: Skipping sending message K9LOCAL:09aa3cd5-613d-428b-a90e-180ce8fe9b54 (reason: error - Unable to send message)
11-06 08:57:52.015 13010 13028 I MessagingController:  Command 'sendPendingMessages' completed
```

Mail server does not see any connection attempt from K-9 Mail.

Workaround described in #7228 (move stuck message to drafts and send it from there) works.

**Comment by tobiasBora** [comment]
I was also hit by this bug: I unfortunately introduced a typo in my email, but configured properly the SMTP server. Hence the SMTP configuration was fine, but when sending the email, it was sending the email with a wrong identity. In practice, the email was kept into the Outbox, and I was getting a small notification (but very hard to see if you don't know it, meaning the I was thinking the email was sent correctly) with an error `Retries exceeded`, but no more details on the error.

After following the debug instructions in https://github.com/thunderbird/thunderbird-android/wiki/LoggingErrors (using `com.fsck.k9` instead of `thunderbird`, I eventually got the actual error in the log:
```
)
01-15 15:44:05.996  9975 13041 I MessagingController: Sending message with UID K9LOCAL:31ce212f-0e4f-45a0-98a8-107e1f4f40e7
01-15 15:44:06.034  9975 13041 D SmtpTransport: Connecting to smtps.univ-myuniv.fr as smtps.univ-myuniv.fr/X.X.X.X
01-15 15:44:06.135  9975 13041 V SmtpTransport: SMTP <<< 220 smtps.univ-myuniv.fr ESMTP Postfix
01-15 15:44:06.136  9975 13041 D SmtpTransport: SMTP >>> EHLO [127.0.0.1]
01-15 15:44:06.166  9975 13041 V SmtpTransport: SMTP <<< 250-smtps.univ-myuniv.fr
01-15 15:44:06.166  9975 13041 V SmtpTransport: SMTP <<< 250-PIPELINING
01-15 15:44:06.166  9975 13041 V SmtpTransport: SMTP <<< 250-SIZE 25000000
01-15 15:44:06.166  9975 13041 V SmtpTransport: SMTP <<< 250-ETRN
01-15 15:44:06.166  9975 13041 V SmtpTransport: SMTP <<< 250-STARTTLS
01-15 15:44:06.166  9975 13041 V SmtpTransport: SMTP <<< 250-ENHANCEDSTATUSCODES
01-15 15:44:06.166  9975 13041 V SmtpTransport: SMTP <<< 250-8BITMIME
01-15 15:44:06.166  9975 13041 V SmtpTransport: SMTP <<< 250-DSN
01-15 15:44:06.166  9975 13041 V SmtpTransport: SMTP <<< 250 CHUNKING
01-15 15:44:06.168  9975 13041 D SmtpTransport: SMTP >>> STARTTLS
01-15 15:44:06.196  9975 13041 V SmtpTransport: SMTP <<< 220 2.0.0 Ready to start TLS
01-15 15:44:06.328  9975 13041 D SmtpTransport: SMTP >>> EHLO [127.0.0.1]
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger: Ignoring EHLO keyword line: AUTH=PLAIN LOGIN
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger: com.fsck.k9.mail.transport.smtp.SmtpResponseParserException: EHLO keyword contains invalid character
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.parserError(SmtpResponseParser.kt:414)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.checkAndNormalizeEhloKeyword(SmtpResponseParser.kt:138)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.parseEhloLine(SmtpResponseParser.kt:122)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.mail.transport.smtp.SmtpResponseParser.readHelloResponse(SmtpResponseParser.kt:108)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendHello(SmtpTransport.kt:303)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.mail.transport.smtp.SmtpTransport.open$smtp(SmtpTransport.kt:126)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:346)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:146)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1544)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.controller.MessagingController$5.run(MessagingController.java:1429)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:221)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java:0)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:162)
01-15 15:44:06.406  9975 13041 V SmtpTransport$logger:  at java.lang.Thread.run(Thread.java:923)
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250-smtps.univ-myuniv.fr
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250-PIPELINING
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250-SIZE 25000000
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250-ETRN
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250-AUTH PLAIN LOGIN
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250-AUTH=PLAIN LOGIN
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250-ENHANCEDSTATUSCODES
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250-8BITMIME
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250-DSN
01-15 15:44:06.408  9975 13041 V SmtpTransport: SMTP <<< 250 CHUNKING
01-15 15:44:06.415  9975 13041 D SmtpTransport: SMTP >>> *sensitive*
01-15 15:44:06.442  9975 13041 V SmtpTransport: SMTP <<< 235 2.7.0 [omitted]
01-15 15:44:06.447  9975 13041 D SmtpTransport: SMTP >>> MAIL FROM:<me@typointhisadrress-myuniv.fr> BODY=8BITMIME
01-15 15:44:06.449  9975 13041 D SmtpTransport: SMTP >>> RCPT TO:<mytestemail@gmail.com>
01-15 15:44:06.484  9975 13041 V SmtpTransport: SMTP <<< 250 2.1.0 Ok
01-15 15:44:06.579  9975 13041 V SmtpTransport: SMTP <<< 450-4.1.8 <me@typointhisadrress-myuniv.fr>: Sender address rejected: Domain not found
01-15 15:44:06.579  9975 13041 V SmtpTransport: SMTP <<< 450 4.1.8 Acces refuse - Veuillez contacter l'assistance
01-15 15:44:06.580  9975 13041 D SmtpTransport: SMTP >>> QUIT
01-15 15:44:06.586  9975 13041 E MessagingController: Failed to send message
01-15 15:44:06.586  9975 13041 E MessagingController: com.fsck.k9.mail.transport.smtp.NegativeSmtpReplyException: <me@typointhisadrress-myuniv.fr>: Sender address rejected: Domain not found Acces refuse - Veuillez contacter l'assistance
01-15 15:44:06.586  9975 13041 E MessagingController:   at com.fsck.k9.mail.transport.smtp.SmtpTransport.buildNegativeSmtpReplyException(SmtpTransport.kt:488)
01-15 15:44:06.586  9975 13041 E MessagingController:   at com.fsck.k9.mail.transport.smtp.SmtpTransport.readPipelinedResponse(SmtpTransport.kt:510)
01-15 15:44:06.586  9975 13041 E MessagingController:   at com.fsck.k9.mail.transport.smtp.SmtpTransport.sendMessage(SmtpTransport.kt:369)
01-15 15:44:06.586  9975 13041 E MessagingController:   at com.fsck.k9.backend.imap.ImapBackend.sendMessage(ImapBackend.kt:146)
01-15 15:44:06.586  9975 13041 E MessagingController:   at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:1544)
01-15 15:44:06.586  9975 13041 E MessagingController:   at com.fsck.k9.controller.MessagingController$5.run(MessagingController.java:1429)
01-15 15:44:06.586  9975 13041 E MessagingController:   at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:221)
01-15 15:44:06.586  9975 13041 E MessagingController:   at com.fsck.k9.controller.MessagingController.-$$Nest$mrunInBackground(MessagingController.java:0)
01-15 15:44:06.586  9975 13041 E MessagingController:   at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:162)
01-15 15:44:06.586  9975 13041 E MessagingController:   at java.lang.Thread.run(Thread.java:923)
01-15 15:44:06.602  9975 13041 V LockableDatabase: LockableDatabase: Transaction ended, took 12 ms / com.fsck.k9.mailstore.LocalMessage.setFlag(LocalMessage.java:256)
01-15 15:44:06.617  9975 13041 V MessagingController: Skipping sending message K9LOCAL:faff707e-09dd-4a12-9af6-6ae97c9a4abc (reason: retries_exceeded - null)
01-15 15:44:06.620  9975 13041 V MessagingController: Skipping sending message K9LOCAL:e80f0f85-71eb-402e-91ef-27a0262108a5 (reason: retries_exceeded - null)
01-15 15:44:06.622  9975 13041 V MessagingController: Skipping sending message K9LOCAL:3d836e49-b934-42c6-b90c-ec0dbc24479c (reason: retries_exceeded - null)
01-15 15:44:06.625  9975 13041 V MessagingController: Skipping sending message K9LOCAL:d9384e85-0a09-4fee-814d-e53f5e4ed8cc (reason: retries_exceeded - null)
01-15 15:44:06.628  9975 13041 V MessagingController: Skipping sending message K9LOCAL:e66286ef-cacc-43aa-8809-6d87c4440f01 (reason: retries_exceeded - null)
01-15 15:44:06.631  9975 13041 V MessagingController: Skipping sending message K9LOCAL:5b1a5e55-77b1-47c0-8bcc-3ef8ec630438 (reason: retries_exceeded - null)
01-15 15:44:06.633  9975 13041 V MessagingController: Skipping sending message K9LOCAL:57fc57bc-b94d-4b17-b778-bd9e56a31eb1 (reason: retries_exceeded - null)
01-15 15:44:06.636  9975 13041 V MessagingController: Skipping sending message K9LOCAL:1f624c77-9d42-4dde-9a70-b20af8ec9d8d (reason: retries_exceeded - null)
01-15 15:44:06.639  9975 13041 V MessagingController: Skipping sending message K9LOCAL:5b757aca-c380-4f8f-9b54-0c340186480b (reason: retries_exceeded - null)
01-15 15:44:06.656  9975 13041 I MessagingController:  Command 'sendPendingMessages' completed
01-15 15:44:06.657  9975 13041 I MessagingController: Running command 'syncINBOX', seq = 68 (background priority)
01-15 15:44:06.658  9975 13041 V MessagingController: Folder INBOX was last synced @ mer. janv. 15 14:43:56 GMT+01:00 2025
01-15 15:44:06.659  9975 13041 D MessagingController: Last folder list refresh @ mer. janv. 15 15:43:43 GMT+01:00 2025. Not refreshing now.
```

**Comment by mhf1998** [comment]
Hi. So after all this time, despite the fact that this issue has repeatedly affected multiple users, and it impacts one of the core functionalities of the app — **sending emails** — has it still not been treated as a **high-priority issue** and still hasn't been fixed? @kewisch 

In my opinion, this is a **major problem**. As I mentioned, it directly affects a critical operation of the app, and for users who encounter this scenario, it can make using the app **very frustrating**.

Has anyone started implementing the suggestions that @cketti  provided?
Is it currently being worked on?
Or is no one taking any steps to fix this issue — not even improving the error messages shown to the user?

I believe that even if there's no time right now to fix the **root cause**, at the very least, the **error messaging** could be improved — so users understand what’s going wrong when this scenario occurs, without having to dig through logs, search issues, or open new ones.

**Comment by mhf1998** [comment]
> * Retry sending messages that have exceeded the maximum retry count when the user selects "send messages" from the Outbox menu
> 
>     * Display an error indicator in the message list for messages that failed to send with a permanent error
> 
>     * For messages that failed to send permanently display an error indicator in the message view and allow the user to see the error message from the server (and date of last send attempt)
> 
>     * Decouple sending messages from checking for new messages


Would it be possible for you to explain the first and fourth solutions in more detail?

Regarding the first solution: do you mean that when the "Send Messages" button is clicked, we should reset the status? Do we need to reset the threshold, or do something else?

And regarding the fourth solution: in your opinion, what problem does this solution actually solve? It might help a bit if the issue is just a slow network, but what if the reason we reach this retry-exceeded state is something like a blocked outgoing port? How would this solution help in that situation?

@kewisch

**Comment by kewisch** [comment]
There is some work ongoing that would help with this, but we don't have any quick fixes at the moment. #8831 gives us the infrastructure we need to display error indicators in the message list. #8834 will improve reliability on our synchronization, which can help with re-sending messages and potentially decouple sending from receiving.

I know it seems bad on the surface, but overall people are able to send their email so it hasn't quite bubbled up to the level where we'd drop everything and hack in a fix.

Hope this helps a bit. I'd love to fix all the high priority issues but then we probably need a new priority level within :-)

**Comment by mhf1998** [comment]
> There is some work ongoing that would help with this, but we don't have any quick fixes at the moment. [#8831](https://github.com/thunderbird/thunderbird-android/issues/8831) gives us the infrastructure we need to display error indicators in the message list. [#8834](https://github.com/thunderbird/thunderbird-android/issues/8834) will improve reliability on our synchronization, which can help with re-sending messages and potentially decouple sending from receiving.
> 
> I know it seems bad on the surface, but overall people are able to send their email so it hasn't quite bubbled up to the level where we'd drop everything and hack in a fix.
> 
> Hope this helps a bit. I'd love to fix all the high priority issues but then we probably need a new priority level within :-)

Thank you for your explanations.
The explanations you provided were for solutions two and three, and based on the details of the issues you shared, it's clear that significant work still remains for those two items.

However, with due respect, your explanations did not address solutions one and four. Those solutions still remain unclear to me, and my questions about them still stand. I'd appreciate it if you could also provide explanations regarding items one and four(I’m talking about solutions #1 and #4 from the first message by cketti).

**Comment by mhf1998** [comment]
> There is some work ongoing that would help with this, but we don't have any quick fixes at the moment. [#8831](https://github.com/thunderbird/thunderbird-android/issues/8831) gives us the infrastructure we need to display error indicators in the message list. [#8834](https://github.com/thunderbird/thunderbird-android/issues/8834) will improve reliability on our synchronization, which can help with re-sending messages and potentially decouple sending from receiving.
> 
> I know it seems bad on the surface, but overall people are able to send their email so it hasn't quite bubbled up to the level where we'd drop everything and hack in a fix.
> 
> Hope this helps a bit. I'd love to fix all the high priority issues but then we probably need a new priority level within :-)


Thank you for your explanations.
The explanations you provided were for solutions two and three and fourth, and based on the details of the issues you shared, it's clear that significant work still remains for those three items.

However, with due respect, your explanations did not address first solution. this solution still remain unclear to me, and my questions about that still stand. I'd appreciate it if you could also provide explanations regarding items one (I’m referring to the first  solution mentioned in cketti's initial message). 
@kewisch 

Also, I’ve reviewed the Epic related to the fourth solution (changing the sync mechanism), but I still have doubts about it—it’s not clear to me how this addresses the core issue.
in your opinion, what problem does this solution actually solve? It might help a bit if the issue is just a slow network, but what if the reason we reach this retry-exceeded state is something like a blocked outgoing port? How would this solution help in that situation?
@kewisch

**Comment by gsauthof** [comment]
@kewisch [wrote](https://github.com/thunderbird/thunderbird-android/issues/4602#issuecomment-3113458891)

> I know it seems bad on the surface, but overall people are able to send their email so it hasn't quite bubbled up to the level where we'd drop everything and hack in a fix.

Well, with mails stuck in the outbox people aren't able to send out these mails in a reasonable fashion.

TBH, it took me some time to discover a work-around for this.

My work-around is:

1. go to the outbox
2. open first stuck message
3. open message context menu (not to be confused with top row context menu, same vertical three buttons!)
4. select 'Edit as new message'
5. send the 'edited' message
6. go back to outbox
7. select message - that now hopefully was sent out successfully - and delete it even though trust in the error handling of k9 has eroded a bit, as this point
8. goto step 1 in case more stuck messages accumulated in the outbox, since it took some time to discover such a workaround

Of course, this is very tedious and error prone.

It took me some more time to discover this issue, which is perhaps not too surprising giving the deteriorating quality of web search, in general. First I discovered a bunch of k9 [discourse](https://forum.k9mail.app/t/messages-stuck-in-outbox/7784) [forum](https://forum.k9mail.app/t/message-still-stuck-forever-in-outbox/13326) [posts](https://forum.k9mail.app/t/emails-stuck-in-outbox-with-poor-4g/13518) without much answers or solutions, followed by closed github issues.

I wouldn't be surprised if less technical (or patient) users would simply dump k9 in the face of such a user experience.

**Comment by abuesen** [comment]
I didn't want to spam the issue tracker, so I haven't commented until now. I’ve been watching this issue for months. It was my expectation that this major problem would be addressed by now.

You can find several complaints regarding this behavior. Average users are not able to solve this problem on their own. Some of my friends have already switched to other clients.

So: No, not everyone is able to resolve the situation themselves. And yes, they just dump K-9.

The main purpose of an email client is to ensure that emails are sent reliably. This is currently not the case because the app does not recover from the error itself, and the error message is too easy to miss.

Maybe it could place an NDR in the inbox? Regardless, it should report errors clearly, visibly, and permanently.

**Comment by am312** [comment]
For me, most (not all) of the emails stuck in the outbox were successfully sent.

**Comment by NeonLogicHub** [comment]
Hey guys. New user on Android. Also have this issue. Only thing I found that works is to move the messagem to the drafts folder and resend. Then it goes. Sucks... 

app is kind of cool....

**Comment by ymollard** [comment]
Also impacted by this issue with v22.0. To improve UX temporarily, could the not-localized "retries exceeded" notification detail be replaced by a Proper (and localized) "_Retries exceeded. Empty the send box of a@b.com if it persists_" to help the user understand what is going on?
