### ISSUE TITLE
crash rendering some mails

### ISSUE THREAD

**Issue by traumschule** [k9mail/k-9#4665]
### Expected behavior
k9 renders every mail without crash

### Actual behavior
Sometimes k9 closes repeatedly on specific mails

### Steps to reproduce
open mail that let k9 crash before

### Environment
K-9 Mail version: 5.6.00

Android version: 9

Account type: IMAP

### Log
```
04-13 19:54:32.567  1266  1288 I ActivityManager: Start proc 30824:com.android.chrome:sandboxed_process1/u0i328 for webview_service com.fsck.k9/org.chromium.content.app.SandboxedProcessService1
04-13 19:54:32.558 30710 30710 D NetworkManagementSocketTagger: tagSocket(164) with statsTag=0xffffffff, statsUid=-1
04-13 19:54:32.568 30824 30824 E Zygote  : accessInfo : 0
04-13 19:54:32.570 30710 30739 V ImapResponseParser: conn221036571<<<#null# [SEARCH, 152598]
04-13 19:54:32.571 30710 30739 V ImapResponseParser: conn221036571<<<#32# [OK, Search completed (0.001 + 0.000 secs).]
04-13 19:54:32.571 30710 30739 I MessagingController: Got new pushed email messages for account $account, folder INBOX
04-13 19:54:32.572 30710 30730 I MessagingController: Running command 'Push messageArrived of account $account, folder INBOX', seq = 10 (background priority)
04-13 19:54:32.590 30824 30824 I dboxed_process: report jit thread pid = 30829
04-13 19:54:32.591 30824 30824 E dboxed_process: Not starting debugger since process cannot load the jdwp agent.
04-13 19:54:32.615  1266  2124 I ActivityManager: DSS on for com.fsck.k9 and scale is 1.0
04-13 19:54:32.617  1266  2124 D MultiDisplayManager: init process display: set packageProcessId, displayId=0, same_package_proc=ProcessRecord{84c5926d0 30710:com.fsck.k9/u0a186}, app=ProcessRecord{15e0cb3d0 30824:com.android.chrome:sandboxed_process1/u0a186i328}
04-13 19:54:32.626   492  2327 V APM_AudioPolicyManager: AudioPolicyManager:setRecordSilenced(uid:99328, silenced:0)
04-13 19:54:32.669 30824 30824 I dboxed_process: Starting a blocking GC Alloc
04-13 19:54:32.669 30824 30824 I dboxed_process: Starting a blocking GC Alloc
04-13 19:54:32.696 30824 30824 I dboxed_process: Alloc concurrent copying GC freed 26620(16MB) AllocSpace objects, 0(0B) LOS objects, 94% free, 1006KB/18MB, paused 548us total 26.060ms
04-13 19:54:32.716 30824 30824 I cr_ChildProcessService: Creating new ChildProcessService pid=30824
04-13 19:54:32.726 30824 30838 I cr_LibraryLoader: Time to load native libraries: 0 ms
04-13 19:54:32.738 30824 30838 I chromium: [INFO:library_loader_hooks.cc(51)] Chromium logging enabled: level = 0, default verbosity = 0
04-13 19:54:32.738 30824 30838 I cr_LibraryLoader: Expected native library version number "79.0.3945.116", actual native library version number "79.0.3945.116"
04-13 19:54:32.819  2506  2506 D io_stats: !@ 179,0 r 4537274 181826954 w 7144123 47119716 d 133277 16096280 f 3113917 3121712 iot 5732340 785382 th 51200 0 0 pt 0 inp 0 0 153387.517
04-13 19:54:32.822 30710 30730 V MessagingController: Message with uid 152598 is present in the local store
04-13 19:54:32.823 30710 30730 D MessagingController: SYNC: Have 0 unsynced messages
04-13 19:54:32.823 30710 30730 D MessagingController: SYNC: Have 0 large messages and 0 small messages out of 0 unsynced messages
04-13 19:54:32.823 30710 30730 D MessagingController: SYNC: Fetching 0 small messages for folder INBOX
04-13 19:54:32.824 30710 30730 D MessagingController: SYNC: Done fetching small messages for folder INBOX
04-13 19:54:32.824 30710 30730 D MessagingController: SYNC: Fetching large messages for folder INBOX
04-13 19:54:32.825 30710 30730 D MessagingController: SYNC: Done fetching large messages for folder INBOX
04-13 19:54:32.825 30710 30730 D MessagingController: SYNC: About to sync flags for 1 remote messages for folder INBOX
04-13 19:54:32.826 30710 30730 V ImapConnection: conn221036571>>> 33 UID FETCH 152598 (UID FLAGS)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer: Font Cache (CPU):
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:   Size: 136.50 kB 
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:   Glyph Count: 32 
04-13 19:54:32.968 30710 30743 E OpenGLRenderer: CPU Caches:
04-13 19:54:32.968 30710 30743 E OpenGLRenderer: GPU Caches:
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:   SW Path Mask:
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:     Texture: 80.50 KB (65 entries)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 1):       28224 Byte (count:3)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 2):       20140 Byte (count:2)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 3):       19600 Byte (count:15)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 4):       12544 Byte (count:14)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 5):        9216 Byte (count:2)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 6):        6084 Byte (count:1)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 7):        3136 Byte (count:1)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 8):        1406 Byte (count:33)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 9):        1369 Byte (count:2)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture(10):        1368 Byte (count:7)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          .......   
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:   Other:
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:     Buffer Object: 63.00 KB (2 entries)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:   Image:
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:     Texture: 610.43 KB (45 entries)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:   Scratch:
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:     RenderTarget: 13.50 MB (2 entries)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:     Buffer Object: 160.03 KB (6 entries)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:     Texture: 583.25 KB (10 entries)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 1):      524288 Byte (count:1)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 2):       28224 Byte (count:1)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Texture( 3):       13312 Byte (count:1)
04-13 19:54:32.968 30710 30743 E OpenGLRenderer:          Te
04-13 19:54:32.970 30710 30710 W System.err: java.lang.IllegalStateException: Unable to create layer for FrameLayout, size 768x4288 max size 8192 color type 4 has context 1
04-13 19:54:32.971 30710 30710 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
04-13 19:54:32.971 30710 30710 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:326)
04-13 19:54:32.971 30710 30710 W System.err: 	at android.os.Looper.loop(Looper.java:181)
04-13 19:54:32.971 30710 30710 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7094)
04-13 19:54:32.971 30710 30710 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-13 19:54:32.971 30710 30710 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-13 19:54:32.971 30710 30710 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
04-13 19:54:32.977 30710 30710 F chromium: [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
04-13 19:54:32.978 30710 30710 F libc    : Fatal signal 5 (SIGTRAP), code 4 (TRAP_HWBKPT), fault addr 0x90f97696 in tid 30710 (com.fsck.k9), pid 30710 (com.fsck.k9)
...
04-13 19:54:33.152 30850 30850 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-13 19:54:33.152 30850 30850 F DEBUG   : Build fingerprint: 'samsung/SCRUBBED:user/release-keys'
04-13 19:54:33.152 30850 30850 F DEBUG   : Revision: '6'
04-13 19:54:33.152 30850 30850 F DEBUG   : ABI: 'arm'
04-13 19:54:33.152 30850 30850 F DEBUG   : pid: 30710, tid: 30710, name: com.fsck.k9  >>> com.fsck.k9 <<<
04-13 19:54:33.152 30850 30850 F DEBUG   : signal 5 (SIGTRAP), code 4 (TRAP_HWBKPT), fault addr 0x90f97696
04-13 19:54:33.152 30850 30850 F DEBUG   : Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
04-13 19:54:33.152 30850 30850 F DEBUG   : '
04-13 19:54:33.152 30850 30850 F DEBUG   :     r0  00000000  r1  00000000  r2  7fffffff  r3  00000000
04-13 19:54:33.152 30850 30850 F DEBUG   :     r4  0000004f  r5  be98f678  r6  92791000  r7  9275ba94
04-13 19:54:33.152 30850 30850 F DEBUG   :     r8  be98f224  r9  be98f670  r10 be98f674  r11 be98f224
04-13 19:54:33.153 30850 30850 F DEBUG   :     ip  be98f1e8  sp  be98f210  lr  a861019d  pc  90f97696
04-13 19:54:33.154 30850 30850 F DEBUG   : 
04-13 19:54:33.154 30850 30850 F DEBUG   : backtrace:
04-13 19:54:33.154 30850 30850 F DEBUG   :     #00 pc 018ea696  /data/app/com.android.chrome-InHPUcGRv54FoPcu2s4uEA==/base.apk (offset 0xba4000)
04-13 19:54:33.177 30710 30730 I MessagingController: messagesArrived newCount = 0, unread count = 1660
04-13 19:54:33.179  1266  1286 V MARsPolicyManager: onAppWidgetManagerActions pkgName = com.fsck.k9, action = android.appwidget.action.APPWIDGET_UPDATE, userId = 0
...
04-13 19:54:34.890  1266 30853 W ActivityManager: crash : com.fsck.k9,0
04-13 19:54:34.893  1266 30853 W ActivityManager:   Force finishing activity com.fsck.k9/.activity.MessageList
...
04-13 19:54:35.175   495  2512 D Layer   : [87532e1 Application Error: com.fsck.k9#0]::reparent oldParent:[WindowToken{112aeeb android.view.ViewRootImpl$W@13b623a}#0], newParent:[Surface(name=87532e1 Application Error: com.fsck.k9)/@0xa5e0e8e - animation-leash#0]
...
04-13 19:54:35.256  1266  2040 D GamePkgDataHelper: getSosPolicy(). com.sec.android.app.launcher
04-13 19:54:35.262  1266  1300 D WindowManager: reportFocusChangedSerialized, focused=false, inTouchMode=true, win=Window{e4f6254 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
04-13 19:54:35.265  1266  1300 E WindowManager: RemoteException occurs on reporting focusChanged, w=Window{e4f6254 u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
04-13 19:54:35.265  1266  1300 E WindowManager: android.os.DeadObjectException
04-13 19:54:35.265  1266  1300 E WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
04-13 19:54:35.265  1266  1300 E WindowManager: 	at android.os.BinderProxy.transact(Binder.java:1145)
04-13 19:54:35.265  1266  1300 E WindowManager: 	at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:500)
04-13 19:54:35.265  1266  1300 E WindowManager: 	at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3998)
04-13 19:54:35.265  1266  1300 E WindowManager: 	at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5547)
04-13 19:54:35.265  1266  1300 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-13 19:54:35.265  1266  1300 E WindowManager: 	at android.os.Looper.loop(Looper.java:214)
04-13 19:54:35.265  1266  1300 E WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:65)
04-13 19:54:35.265  1266  1300 E WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
04-13 19:54:35.269  1266  2019 I WindowManager: commitFinishDrawingLocked: mDrawState=READY_TO_SHOW Surface(name=NavigationBar[1750])/@0xfb537fd
...
04-13 19:54:35.485  1266  1535 I WindowManager: reset, Reparenting to original parent, shouldDeferScheduleAnimation=false, destroyLeash=true, surface=Surface(name=87532e1 Application Error: com.fsck.k9)/@0xa5e0e8e, parent=Surface(name=WindowToken{112aeeb android.view.ViewRootImpl$W@13b623a})/@0x24fa6af, parentNativeHandle=android.os.BinderProxy@f8be9d8, caller=com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:97 com.android.server.wm.-$$Lambda$SurfaceAnimator$SIBia0mND666K8lMCPsoid8pUTI.run:4 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$1:104 com.android.server.wm.-$$Lambda$SurfaceAnimator$vdRZk66hQVbQCvVXEaQCT1kVmFc.onAnimationFinished:4 com.android.server.wm.LocalAnimationAdapter.lambda$startAnimation$0:74 
04-13 19:54:35.485  1266  1535 D SurfaceControl: reparent is called, sc=Surface(name=87532e1 Application Error: com.fsck.k9)/@0xa5e0e8e, newParentHandle=android.os.BinderProxy@f8be9d8, transaction=android.view.SurfaceControl$Transaction@b30859a
04-13 19:54:35.486  1266  1535 D SurfaceControl: destroy(transaction), animation-leash is destroyed, sc=Surface(name=Surface(name=87532e1 Application Error: com.fsck.k9)/@0xa5e0e8e - animation-leash)/@0xb0d7abc, transaction=android.view.SurfaceControl$Transaction@b30859a, caller=com.android.server.wm.SurfaceAnimator.reset:344 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:97 com.android.server.wm.-$$Lambda$SurfaceAnimator$SIBia0mND666K8lMCPsoid8pUTI.run:4 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$1:104 com.android.server.wm.-$$Lambda$SurfaceAnimator$vdRZk66hQVbQCvVXEaQCT1kVmFc.onAnimationFinished:4 com.android.server.wm.LocalAnimationAdapter.lambda$startAnimation$0:74 com.android.server.wm.-$$Lambda$LocalAnimationAdapter$X--EomqUvw4qy89IeeTFTH7aCMo.run:4

**Comment by cketti** [comment]
This is most likely a device specific issue. See #4437.

**Comment by cketti** [comment]
K-9 Mail always renders messages inside a WebView. 

If you're able to reliably reproduce the crash and you have development experience please try to implement the workarounds and see if any of them actually work. I don't see this issue being fixed otherwise.

**Comment by traumschule** [comment]
It's an interesting issue because it doesn't happen everytime even with mails it crashed on before. I was just able to let it crash three times in a row on the same mail but the 4th time it was rendered just fine.
As a side-effect of the crash the operation on the previous mail like deletion is lost which could mean there are other factors for a crash like resource consumption. In the linked SE post others mentioned similar irregularities.

**Comment by PhotoKevin** [comment]
I've been running into this too. I finally got around to capturing a log and when I came to post an issue, here it was.

The relevant portion of the log seems to be the same:
```
05-05 16:48:37.547  7995  7995 E MessageQueue-JNI: Exception in MessageQueue callback: dispatchVsync
05-05 16:48:37.549  7995  7995 E MessageQueue-JNI: java.lang.IllegalStateException: Unable to create layer for FrameLayout, size 832x4800 max size 8192 color type 4 has context 1
05-05 16:48:37.549  7995  7995 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-05 16:48:37.549  7995  7995 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:326)
05-05 16:48:37.549  7995  7995 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:183)
05-05 16:48:37.549  7995  7995 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:7266)
05-05 16:48:37.549  7995  7995 E MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)
05-05 16:48:37.549  7995  7995 E MessageQueue-JNI: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
05-05 16:48:37.549  7995  7995 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```
If you can't really fix it, could you at least catch the exception and just show a message?

**Comment by PhotoKevin** [comment]
I have been attempting to track this down. A typical scenario is that I download new mail. Then I click on a message. K9 crashes. I restart and the message partly displays. I hit the button to download the rest and K9 crashes. I restart and then the message likely displays. Based on this, I have some suspicions, but it would be really nice if I could somehow reset the internal version of the message so that I could repeat the issue.   Is there any way to clear out the internal mail data such that K9 starts back like this is a brand new message? As it is, I'm getting one or two debug runs through per week.

Er, a clarification. When I try to read email on my tablet and it crashes, and if I'm at home, I hook my tablet up in the Android Studio debugger and use a version of K9 I've built from the latest source code. It's that debug version who's DB I want to reset. I might be able to just wipe the data but then I'd have to go through the bother of resetting up the accounts.

**Comment by cketti** [comment]
You can remove all downloaded messages from a folder under `Manage folders > [Folder] > (action bar menu) > Clear local messages`.

**Comment by PhotoKevin** [comment]
I haven't had any real luck with fixing this. I've convinced myself that it happening because it's displaying the message while it is downloading and thus changing.   There doesn't seem to be anyway to force K9 to download the entire message up front.

I've also convinced myself that it's an OS mishandling of a native code exception.
