### ISSUE TITLE
MessagingException: LocalFolder.open(): Folder not found: null (6) for POP3 account

### ISSUE THREAD

**Issue by eMPee584** [k9mail/k-9#4848]
After restoring K9 from a TitaniumBackup from my previous phone, it dies whenever trying to open an POP3 account. Two IMAP accounts display and work normally.. it crashes when switching to the POP3 one with

```
06-23 21:31:38.130 16184 16184 E AndroidRuntime: FATAL EXCEPTION: main
06-23 21:31:38.130 16184 16184 E AndroidRuntime: Process: com.fsck.k9, PID: 16184
06-23 21:31:38.130 16184 16184 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.MessageList}: java.lang.RuntimeException: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: null (6)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2825)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2900)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(Unknown Source:0)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:251)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6589)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
06-23 21:31:38.130 16184 16184 E AndroidRuntime: Caused by: java.lang.RuntimeException: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: null (6)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:524)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.decodeArguments(MessageListFragment.java:468)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onCreate(MessageListFragment.java:317)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1255)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1138)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:136)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1989)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2629)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2577)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.activity.MessageList.onStart(MessageList.java:570)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:6992)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2788)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        ... 9 more
06-23 21:31:38.130 16184 16184 E AndroidRuntime: Caused by: com.fsck.k9.mail.MessagingException: LocalFolder.open(): Folder not found: null (6)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:178)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.mailstore.LocalFolder$1.doDbWork(LocalFolder.java:160)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:273)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.mailstore.LocalFolder.open(LocalFolder.java:160)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.fragment.MlfUtils.getOpenFolder(MlfUtils.java:28)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.getFolderInfoHolder(MessageListFragment.java:521)
06-23 21:31:38.130 16184 16184 E AndroidRuntime:        ... 29 more


```
K-9 Mail version:
5.717
Backup from 5.716

Android version:
8.0.0. Stock Xperia
Backup from 8.1.0 LOS 15.1

Account type (IMAP, POP3, WebDAV/Exchange):
POP3 + several IMAP (which seem to work as i get notifications and can open mails from thereeba)

PS: only just found there's import/export settings in K9. Going to remove that account after restoring with TiBa and import only these specific settings with K9's own settings import.]

**Comment by cketti** [comment]
Sorry, TitaniumBackup is not a supported way to get K-9 Mail from one phone to another. If this causes a problem you're on your own.
