### ISSUE TITLE
Crash on create new mail or reply

### ISSUE THREAD

**Issue by danielpublic** [k9mail/k-9#4865]
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Should be able to write/reply mail

### Actual behavior
Crashes

### Steps to reproduce
1. Install k9 from fdroid on a doogee s60 
2. Configure client
3. Try to create or reply to a mail

### Environment
K-9 Mail version:
5.717
Android version:
7
Account type (IMAP, POP3, WebDAV/Exchange):
Gmail/imap

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here: 

```
07-05 18:48:12.670 I/ActivityManager(1125): startActivityLocked intent:Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.MessageList }
07-05 18:48:12.671 I/ActivityManager(1125): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.MessageList} from uid 10140 on display 0
07-05 18:48:12.714 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:12.715 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:12.716 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:12.717 I/WindowManager(1125): lockCanvas, mToken =AppWindowToken{22f2190 token=Token{d6ddc42 ActivityRecord{9b2228d u0 com.fsck.k9/.activity.MessageList t24}}}
07-05 18:48:12.720 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:12.787 I/ActivityManager(1125): Start proc 24360:com.fsck.k9/u0a194 for activity com.fsck.k9/.activity.MessageList
07-05 18:48:12.808 I/libPerfService(1125): [perfNotifyAppState] foreground:com.fsck.k9, pid:24360
07-05 18:48:12.830 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:12.835 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:12.838 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:12.846 W/System  (24360): ClassLoader referenced unknown path: /data/app/com.fsck.k9-1/lib/arm64
07-05 18:48:13.156 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:13.157 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:13.247 I/art     (24360): Compiler allocated 11MB to compile void com.fsck.k9.AccountPreferenceSerializer.loadAccount(com.fsck.k9.Account, com.fsck.k9.preferences.Storage)
07-05 18:48:13.607 I/BufferQueueConsumer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:0,p:-1,c:372) setConsumerName: com.fsck.k9/com.fsck.k9.activity.MessageList
07-05 18:48:13.607 I/BufferQueueConsumer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:0,p:-1,c:372) setDefaultBufferSize: width=1 height=1
07-05 18:48:13.614 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:13.625 I/BufferQueueConsumer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:0,p:-1,c:372) setDefaultBufferSize: width=1080 height=1920
07-05 18:48:13.632 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:13.654 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:1,p:24360,c:372) connect(P): api=1 producer=(24360:com.fsck.k9) producerControlledByApp=true
07-05 18:48:13.778 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:1,p:24360,c:372) new GraphicBuffer needed
07-05 18:48:13.819 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:1,p:24360,c:372) new GraphicBuffer needed
07-05 18:48:13.869 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:13.871 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:13.874 I/ActivityManager(1125): Displayed com.fsck.k9/.activity.MessageList: +1s111ms
07-05 18:48:13.879 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:1,p:24360,c:372) new GraphicBuffer needed
07-05 18:48:13.890 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:13.891 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:13.989 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:13.993 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:15.509 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:1,p:24360,c:372) queueBuffer: fps=5.92 dur=1690.48 max=1162.91 min=5.82
07-05 18:48:15.511 I/ActivityManager(1125): startActivityLocked intent:Intent { act=com.fsck.k9.intent.action.COMPOSE cmp=com.fsck.k9/.activity.MessageCompose (has extras) }
07-05 18:48:15.511 I/ActivityManager(1125): START u0 {act=com.fsck.k9.intent.action.COMPOSE cmp=com.fsck.k9/.activity.MessageCompose (has extras)} from uid 10194 on display 0
07-05 18:48:15.514 E/AndroidRuntime(24360): Process: com.fsck.k9, PID: 24360
07-05 18:48:15.514 E/AndroidRuntime(24360): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.fsck.k9/com.fsck.k9.activity.MessageCompose}; have you declared this activity in your AndroidManifest.xml?
07-05 18:48:15.514 E/AndroidRuntime(24360): 	at com.fsck.k9.activity.compose.MessageActions.actionCompose(MessageActions.java:31)
07-05 18:48:15.514 E/AndroidRuntime(24360): 	at com.fsck.k9.activity.MessageList.onCompose(MessageList.java:1303)
07-05 18:48:15.514 E/AndroidRuntime(24360): 	at com.fsck.k9.fragment.MessageListFragment.onCompose(MessageListFragment.java:615)
07-05 18:48:15.514 E/AndroidRuntime(24360): 	at com.fsck.k9.activity.MessageList.onOptionsItemSelected(MessageList.java:934)
07-05 18:48:15.517 W/ActivityManager(1125):   Force finishing activity com.fsck.k9/.activity.MessageList
07-05 18:48:15.541 I/AEE_AED (24455): [preset_info] pid: 24360, tid: -1361051648, name: UNKNOWN  >>> com.fsck.k9 <<<
07-05 18:48:15.613 I/BufferQueueConsumer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:0,p:-1,c:372) setConsumerName: Application Error: com.fsck.k9
07-05 18:48:15.613 I/BufferQueueConsumer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:0,p:-1,c:372) setDefaultBufferSize: width=193 height=193
07-05 18:48:15.623 I/BufferQueueConsumer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:0,p:-1,c:372) setDefaultBufferSize: width=1218 height=623
07-05 18:48:15.635 I/BufferQueueProducer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:1125,c:372) connect(P): api=1 producer=(1125:system_server) producerControlledByApp=false
07-05 18:48:15.645 I/BufferQueueProducer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:1125,c:372) new GraphicBuffer needed
07-05 18:48:15.664 I/BufferQueueProducer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:1125,c:372) new GraphicBuffer needed
07-05 18:48:15.674 I/BufferQueueProducer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:1125,c:372) new GraphicBuffer needed
07-05 18:48:16.034 W/ActivityManager(1125): Activity pause timeout for ActivityRecord{9b2228d u0 com.fsck.k9/.activity.MessageList t24 f}
07-05 18:48:16.077 E/SurfaceFlinger(372): renderScreenImplLocked i = 2 name = com.fsck.k9/com.fsck.k9.activity.MessageList visible=1
07-05 18:48:16.077 E/SurfaceFlinger(372): renderScreenImplLocked 222 draw i = 2 name = com.fsck.k9/com.fsck.k9.activity.MessageList
07-05 18:48:16.077 E/SurfaceFlinger(372): renderScreenImplLocked i = 8 name = Application Error: com.fsck.k9 visible=1
07-05 18:48:18.624 I/BufferQueueProducer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:1125,c:372) queueBuffer: fps=0.68 dur=2960.15 max=2950.27 min=9.88
07-05 18:48:18.664 I/ActivityManager(1125): Killing 24360:com.fsck.k9/u0a194 (adj 900): crash
07-05 18:48:18.668 I/WindowManager(1125): Destroying surface Surface(name=com.fsck.k9/com.fsck.k9.activity.MessageList) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.removeLocked:1459 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2662 com.android.server.wm.WindowManagerService.removeWindowLocked:2610 com.android.server.wm.WindowManagerService.removeWindowLocked:2479 com.android.server.wm.AppWindowToken.removeAllWindows:530 com.android.server.wm.AppWindowToken.removeAppFromTaskLocked:326 
07-05 18:48:18.668 I/BufferQueueProducer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:-1,c:372) disconnect(P): api 1
07-05 18:48:18.669 I/BufferQueueConsumer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:-1,c:372) getReleasedBuffers: returning mask 0xfffffffffffffffd
07-05 18:48:18.670 I/BufferQueueProducer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:-1,c:372) disconnect(P): api 1
07-05 18:48:18.675 I/BufferQueueConsumer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:1,p:24360,c:-1) disconnect(C)
07-05 18:48:18.694 I/ActivityManager(1125): startActivityLocked intent:Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.fsck.k9/.activity.MessageList }
07-05 18:48:18.694 I/ActivityManager(1125): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10300000 cmp=com.fsck.k9/.activity.MessageList} from uid 10140 on display 0
07-05 18:48:18.736 I/WindowManager(1125): lockCanvas, mToken =AppWindowToken{cba6f83 token=Token{8655e3d ActivityRecord{a0cd394 u0 com.fsck.k9/.activity.MessageList t24}}}
07-05 18:48:18.744 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:1,p:-1,c:-1) disconnect(P): api 1
07-05 18:48:18.746 I/BufferQueue(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d13865800,id:347,api:1,p:-1,c:-1) ~BufferQueueCore
07-05 18:48:18.753 I/ActivityManager(1125): Start proc 24465:com.fsck.k9/u0a194 for activity com.fsck.k9/.activity.MessageList
07-05 18:48:18.762 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:18.770 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:18.771 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:18.788 I/libPerfService(1125): [perfNotifyAppState] foreground:com.fsck.k9, pid:24465
07-05 18:48:18.805 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:18.816 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:18.820 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:18.821 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:18.826 W/System  (24465): ClassLoader referenced unknown path: /data/app/com.fsck.k9-1/lib/arm64
07-05 18:48:18.909 I/WindowManager(1125): Destroying surface Surface(name=Application Error: com.fsck.k9) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.destroyOrSaveSurface:2103 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:434 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:235 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:183 com.android.server.wm.WindowManagerService$H.handleMessage:8410 android.os.Handler.dispatchMessage:110 
07-05 18:48:18.914 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:18.918 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:18.924 I/BufferQueueConsumer(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:-1,c:-1) disconnect(C)
07-05 18:48:18.925 I/BufferQueue(372): [Application Error: com.fsck.k9](this:0x7d1384f800,id:348,api:1,p:-1,c:-1) ~BufferQueueCore
07-05 18:48:19.139 I/art     (24465): Compiler allocated 11MB to compile void com.fsck.k9.AccountPreferenceSerializer.loadAccount(com.fsck.k9.Account, com.fsck.k9.preferences.Storage)
07-05 18:48:19.256 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.472 I/BufferQueueConsumer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:0,p:-1,c:372) setConsumerName: com.fsck.k9/com.fsck.k9.activity.MessageList
07-05 18:48:19.472 I/BufferQueueConsumer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:0,p:-1,c:372) setDefaultBufferSize: width=1 height=1
07-05 18:48:19.477 I/BufferQueueConsumer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:0,p:-1,c:372) setDefaultBufferSize: width=1080 height=1920
07-05 18:48:19.488 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.489 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.489 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.503 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:24465,c:372) connect(P): api=1 producer=(24465:com.fsck.k9) producerControlledByApp=true
07-05 18:48:19.542 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.544 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.628 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:24465,c:372) new GraphicBuffer needed
07-05 18:48:19.654 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:24465,c:372) new GraphicBuffer needed
07-05 18:48:19.694 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.694 I/ActivityManager(1125): Displayed com.fsck.k9/.activity.MessageList: +964ms
07-05 18:48:19.694 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.701 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:24465,c:372) new GraphicBuffer needed
07-05 18:48:19.705 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.827 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:19.831 I/EyesProtectedService(20470): pn = com.fsck.k9, cn = .activity.MessageList
07-05 18:48:20.236 E/SurfaceFlinger(372): renderScreenImplLocked i = 2 name = com.fsck.k9/com.fsck.k9.activity.MessageList visible=1
07-05 18:48:20.236 E/SurfaceFlinger(372): renderScreenImplLocked 222 draw i = 2 name = com.fsck.k9/com.fsck.k9.activity.MessageList
07-05 18:48:20.295 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:-1,c:372) disconnect(P): api 1
07-05 18:48:20.295 I/BufferQueueConsumer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:-1,c:372) getReleasedBuffers: returning mask 0xffffffffffffffff
07-05 18:48:20.298 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:-1,c:372) disconnect(P): api 1
07-05 18:48:20.744 I/BufferQueueProducer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:-1,c:372) disconnect(P): api -1
07-05 18:48:22.648 I/ActivityManager(1125): Killing 24465:com.fsck.k9/u0a194 (adj 900): remove task
07-05 18:48:22.767 W/InputDispatcher(1125): channel 'd82858c com.fsck.k9/com.fsck.k9.activity.MessageList (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-05 18:48:22.767 E/InputDispatcher(1125): channel 'd82858c com.fsck.k9/com.fsck.k9.activity.MessageList (server)' ~ Channel is unrecoverably broken and will be disposed!
07-05 18:48:22.802 I/WindowManager(1125): WIN DEATH: Window{d82858c u0 com.fsck.k9/com.fsck.k9.activity.MessageList}
07-05 18:48:22.802 W/InputDispatcher(1125): Attempted to unregister already unregistered input channel 'd82858c com.fsck.k9/com.fsck.k9.activity.MessageList (server)'
07-05 18:48:22.802 I/WindowManager(1125): Destroying surface Surface(name=com.fsck.k9/com.fsck.k9.activity.MessageList) called by com.android.server.wm.WindowStateAnimator.destroySurface:2137 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:948 com.android.server.wm.WindowState.removeLocked:1459 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2662 com.android.server.wm.WindowManagerService.removeWindowLocked:2610 com.android.server.wm.WindowState$DeathRecipient.binderDied:1790 android.os.BinderProxy.sendDeathNotice:695 <bottom of call stack> 
07-05 18:48:22.813 I/BufferQueueConsumer(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:-1,c:-1) disconnect(C)
07-05 18:48:22.813 I/BufferQueue(372): [com.fsck.k9/com.fsck.k9.activity.MessageList](this:0x7d10790000,id:351,api:1,p:-1,c:-1) ~BufferQueueCore
```

**Comment by cketti** [comment]
The screen to compose new messages is disabled by default and only enabled after an account has been set up. It seems like this doesn't work properly on your device. Try uninstalling, then reinstalling K-9 Mail. Sometimes that helps to get the app back in a usable state. 
If it still doesn't work you should report this as a bug in the Android version you're using to your device vendor.

**Comment by danielpub** [comment]
The K-9 Mail version: 5.717 through fdroid seems to work. Had uninstall and reinstall and answer 'deny' on the access to my contacts question. Now I can reply and answer without crashes. Thanks for your work on this fine app! :)
