### ISSUE TITLE
Giving K-9 permission before opening it for the first time causes it to crash

### ISSUE THREAD

**Issue by sjl872964789** [k9mail/k-9#4890]
### Expected behavior
K-9 should not crash anyway

### Actual behavior
K-9 crashed，and unless K-9's data is cleared from the system settings, K-9 will never be opened

### Steps to reproduce
------------------------------------------------------------------------------------------------------------
Use the following steps will reproduce the bug (as shown in the phone on the right in the video)
1. Install K-9
2. Give K-9 the required permissions in the system settings
3. Use adb command to start k-9 mail:
```
adb shell am start -n com.fsck.k9/com.fsck.k9.activity.Accounts
```
4. Crash
------------------------------------------------------------------------------------------------------------
Use the following steps will start the K-9 normally (aas shown in the phone on the left in the video)
1. Install K-9
2. Use adb command to start k-9 mail:
```
adb shell am start -n com.fsck.k9/com.fsck.k9.activity.Accounts
```
------------------------------------------------------------------------------------------------------------
From this we can know that the bug is caused by changing permissions

### Environment
K-9 Mail version: 5.600

Android version: Android10.0

### Additional context
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/15941953/88261362-ba6eca00-ccf8-11ea-9b98-6e97edcb66e5.gif)

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
```
07-23 06:41:01.726 23373 23373 E AndroidRuntime: FATAL EXCEPTION: main
07-23 06:41:01.726 23373 23373 E AndroidRuntime: Process: com.google.android.permissioncontroller, PID: 23373
07-23 06:41:01.726 23373 23373 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.preference.PreferenceGroup.getPreferenceCount()' on a null object reference
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at com.android.packageinstaller.permission.ui.handheld.ReviewPermissionsFragment.confirmPermissionsReview(ReviewPermissionsFragment.java:200)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at com.android.packageinstaller.permission.ui.handheld.ReviewPermissionsFragment.onCreate(ReviewPermissionsFragment.java:123)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2596)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:831)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2650)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2600)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7825)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
07-23 06:41:01.726 23373 23373 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
07-23 06:41:38.972 24164 24164 E AndroidRuntime: FATAL EXCEPTION: main
07-23 06:41:38.972 24164 24164 E AndroidRuntime: Process: com.google.android.permissioncontroller, PID: 24164
07-23 06:41:38.972 24164 24164 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int androidx.preference.PreferenceGroup.getPreferenceCount()' on a null object reference
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at com.android.packageinstaller.permission.ui.handheld.ReviewPermissionsFragment.confirmPermissionsReview(ReviewPermissionsFragment.java:200)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at com.android.packageinstaller.permission.ui.handheld.ReviewPermissionsFragment.onCreate(ReviewPermissionsFragment.java:123)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2596)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:831)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1853)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1811)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1717)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2650)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2600)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7825)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7356)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
07-23 06:41:38.972 24164 24164 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by cketti** [comment]
It's not K-9 Mail that is crashing it's `com.google.android.permissioncontroller`. Feel free to report this bug to Google.

Given that 5.7xx uses runtime permissions I believe this will no longer be an issue with the next stable version.
