### ISSUE TITLE
Crash when canceling passphrase input when decrypting messages

### ISSUE THREAD

**Issue by dschuermann** [k9mail/k-9#588]
K-9 crashes when the passphrase input of OpenKeychain is cancelled.

**Comment by Manko10** [comment]
Same here. Stacktrace is as follows:

```
FATAL EXCEPTION: main
    Process: com.fsck.k9.debug, PID: 21609
    java.lang.NullPointerException: Attempt to invoke virtual method 'int org.openintents.openpgp.OpenPgpSignatureResult.getResult()' on a null object reference
            at com.fsck.k9.ui.messageview.OpenPgpHeaderView.displayVerificationResult(OpenPgpHeaderView.java:184)
            at com.fsck.k9.ui.messageview.OpenPgpHeaderView.initializeSignatureHeader(OpenPgpHeaderView.java:164)
            at com.fsck.k9.ui.messageview.OpenPgpHeaderView.setOpenPgpData(OpenPgpHeaderView.java:70)
            at com.fsck.k9.ui.messageview.MessageContainerView.displayMessageViewContainer(MessageContainerView.java:444)
            at com.fsck.k9.ui.messageview.MessageTopView.setMessage(MessageTopView.java:94)
            at com.fsck.k9.ui.messageview.MessageViewFragment.showMessage(MessageViewFragment.java:277)
            at com.fsck.k9.ui.messageview.MessageViewFragment.onDecodeMessageFinished(MessageViewFragment.java:272)
            at com.fsck.k9.ui.messageview.MessageViewFragment.access$1200(MessageViewFragment.java:56)
            at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:751)
            at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:741)
            at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
            at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:451)
            at android.content.Loader.deliverResult(Loader.java:144)
            at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:40)
            at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:15)
            at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
            at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
            at android.os.AsyncTask.finish(AsyncTask.java:651)
            at android.os.AsyncTask.-wrap1(AsyncTask.java)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by alexandre75** [comment]
PR https://github.com/k9mail/k-9/pull/884 fixes this issue
Commit
b3497934ab89bccbc10fabe06ed3e90c52dfb4f1
