### ISSUE TITLE
Some messages do not display with K-9 build from trunk (v 5.106) 

### ISSUE THREAD

**Issue by ConteDiMonteCristo** [k9mail/k-9#741]
I had this happening twice on my own debug-build of k-9 version 5.106.
At first I though it was somehow related to my changes (see pull request #725), but I can reproduce  it with a build from master branch, corresponding to v 5.106. It works on 5.006, official version, instead.

All other messages display fine, apart from these two sent by the same sender (my dentist :smirk: ) and hence formatted similarly. The message is in MIME multipart, with the text in HTML format and three images attached and transferred in Base64.
K-9 tells me that there is a new message in my inbox and I can see the message heading in the message view. When I try to open it, the view is completely blank.
Well, I reproduced it with adb/logcat on and you can reed the exception below.

So in summary:
- It is reproducible
- It happens on builds from trunk
- it looks like a bug
- the same message displays fine on the official 5.006 version from Google play

I am happy to try to fix it in the coming weeks if no one is available.

And here is the error:
```
08-08 18:34:24.798 E/k9      (23103): Error while loading message from database
08-08 18:34:24.798 E/k9      (23103): java.lang.IllegalStateException: Parent is neither a multipart nor a message
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder.loadMessagePart(LocalFolder.java:704)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder.loadMessageParts(LocalFolder.java:663)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder.access$1000(LocalFolder.java:61)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder$7.doDbWork(LocalFolder.java:624)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder$7.doDbWork(LocalFolder.java:615)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:283)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder.fetch(LocalFolder.java:615)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.controller.MessagingController.loadMessage(MessagingController.java:3081)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.ui.message.LocalMessageLoader.loadMessageFromDatabase(LocalMessageLoader.java:58)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.ui.message.LocalMessageLoader.loadInBackground(LocalMessageLoader.java:50)
08-08 18:34:24.798 E/k9      (23103): 	at com.fsck.k9.ui.message.LocalMessageLoader.loadInBackground(LocalMessageLoader.java:16)
08-08 18:34:24.798 E/k9      (23103): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
08-08 18:34:24.798 E/k9      (23103): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
08-08 18:34:24.798 E/k9      (23103): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
08-08 18:34:24.798 E/k9      (23103): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-08 18:34:24.798 E/k9      (23103): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-08 18:34:24.798 E/k9      (23103): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-08 18:34:24.798 E/k9      (23103): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-08 18:34:24.798 E/k9      (23103): 	at java.lang.Thread.run(Thread.java:864)
08-08 18:37:11.318 E/k9      (23103): Error while loading message from database
08-08 18:37:11.318 E/k9      (23103): java.lang.IllegalStateException: Parent is neither a multipart nor a message
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder.loadMessagePart(LocalFolder.java:704)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder.loadMessageParts(LocalFolder.java:663)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder.access$1000(LocalFolder.java:61)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder$7.doDbWork(LocalFolder.java:624)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder$7.doDbWork(LocalFolder.java:615)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.mailstore.LockableDatabase.execute(LockableDatabase.java:283)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.mailstore.LocalFolder.fetch(LocalFolder.java:615)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.controller.MessagingController.loadMessage(MessagingController.java:3081)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.ui.message.LocalMessageLoader.loadMessageFromDatabase(LocalMessageLoader.java:58)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.ui.message.LocalMessageLoader.loadInBackground(LocalMessageLoader.java:50)
08-08 18:37:11.318 E/k9      (23103): 	at com.fsck.k9.ui.message.LocalMessageLoader.loadInBackground(LocalMessageLoader.java:16)
08-08 18:37:11.318 E/k9      (23103): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
08-08 18:37:11.318 E/k9      (23103): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
08-08 18:37:11.318 E/k9      (23103): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
08-08 18:37:11.318 E/k9      (23103): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
08-08 18:37:11.318 E/k9      (23103): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-08 18:37:11.318 E/k9      (23103): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-08 18:37:11.318 E/k9      (23103): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-08 18:37:11.318 E/k9      (23103): 	at java.lang.Thread.run(Thread.java:864)
```

**Comment by ConteDiMonteCristo** [comment]
Found the bug in the code!
**Will submit a pull request asap** (before tomorrow night). This needs to be corrected before the next release and it really is an easy fix.
Basically in some emails "Multipart/" appears with M capitalized, while the string comparison in the code checks only against "multipart/". Hence it needs a toLoweCase() before the startWith comparison,
The build now works with toLowerCase(), and the message appears in the view. Wonder if this happens somewhere else in the code.
