### ISSUE TITLE
still Connection timed out with SSL connection....  

### ISSUE THREAD

**Issue by Dutchglory** [k9mail/k-9#755]
9-Mail version: 1.10
Device make: samsung
Device model: SM-N910F
Android version: 5.0.1

javax.net.ssl.SSLException: Read error: ssl=0xa0f80e00: I/O error during system call, Connection timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:728)
	at java.io.InputStream.read(InputStream.java:162)
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:194)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
	at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:41)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:32)
	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:73)
	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:311)
	at com.fsck.k9.mail.store.imap.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:722)
	at com.fsck.k9.mail.store.imap.ImapStore$ImapFolderPusher$1.run(ImapStore.java:2391)
	at java.lang.Thread.run(Thread.java:818)

other note: make bugreport option within K9 mail, much easier.... 

André

**Comment by cketti** [comment]
Connections timing out is something that just happens in the real world. Can you provide more context?

**Comment by Rocco83** [comment]
Hi,

I Have the same issue.
I Have several IMAP push folders (around 15) and often k9 is not able to send messages.
One workaround is to shut down data and turn it on after a few seconds.
I see also in the status a SetFlagBulk 0/1 in the folders status.

Seems to me stuck trying to do something.
I do not see any error in catlog.

At the same timeframe I have 2 error:
Push error for folder.subfolder
---
K9-Mail version: 5.010
Device make: LGE
Device model: Nexus 5X
Android version: 6.0.1

java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(java.lang.String, boolean, com.fsck.k9.mail.store.ImapStore$UntaggedHandler)' on a null object reference
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:862)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3151)
	at java.lang.Thread.run(Thread.java:818)
---

SocketTimeoutException: read time out
---
K9-Mail version: 5.010
Device make: LGE
Device model: Nexus 5X
Android version: 6.0.1

javax.net.ssl.SSLException: Read error: ssl=0x7f67aaff80: I/O error during system call, Connection timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:705)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
	at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:42)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2925)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:862)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3151)
	at java.lang.Thread.run(Thread.java:818)

**Comment by philipwhiuk** [comment]
Please don't add other errors to the same issue. I've opened #1283 for the push error.

Your underlying issue is still that the connection is timing out due to a poor network connection. In the future these errors will replaced with a more generic 'unable to connect to server' or just not shown at all.

There's nothing to suggest anything other than a network issue here.
