### ISSUE TITLE
Cannot send email from K-9  unless wifi is on.

### ISSUE THREAD

**Issue by tfranklin64** [k9mail/k-9#838]
Sometime in the last 16 hours, the ability for me to send email via cellular data has stopped working.  Sending only works when connected to wifi.  Receiving works just fine.   I can send with same email account via cellular with an apple device using the gmail app.    
This is the error message: 
K9-Mail version: 5.006
Device make: samsung
Device model: SM-G900V
Android version: 5.0

com.fsck.k9.mail.MessagingException: Unable to open connection to SMTP server.
	at com.fsck.k9.mail.transport.SmtpTransport.open(SmtpTransport.java:419)
	at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:504)
	at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:495)
	at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3563)
	at com.fsck.k9.controller.MessagingController$20.run(MessagingController.java:3314)
	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketTimeoutException: failed to connect to smtp.gmail.com/2607:f8b0:4002:c06::6d
(port 465) after 10000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
	at libcore.io.IoBridge.connect(IoBridge.java:122)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
	at java.net.Socket.connect(Socket.java:882)
	at com.fsck.k9.mail.transport.SmtpTransport.open(SmtpTransport.java:228)

**Comment by cketti** [comment]
This is not a bug. Please use the [mailing list](http://groups.google.com/group/k-9-mail) for support requests like this.
