### ISSUE TITLE
StrictMode Closable not closed related to ImapStore

### ISSUE THREAD

**Issue by lambdaupb** [k9mail/k-9#859]
I'm seeing this Exception a lot in my logcat on CM12.1 with some connectivity Issues.

Seeing that #211 was handled, maybe it is of interest.
Thanks for maintaining k9!

```
10-23 16:25:02.246 23082 23104 E StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
10-23 16:25:02.246 23082 23104 E StrictMode: java.lang.Throwable: Explicit termination method 'end' not called
10-23 16:25:02.246 23082 23104 E StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:184)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at java.util.zip.Inflater.<init>(Inflater.java:82)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2573)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapConnection.sendCommand(ImapStore.java:2872)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2921)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2902)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:858)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:904)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.open(ImapStore.java:867)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:1041)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.controller.MessagingController$35.run(MessagingController.java:4506)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
10-23 16:25:02.246 23082 23104 E StrictMode: 	at java.lang.Thread.run(Thread.java:818)
10-23 16:25:02.249 23082 23104 E StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
10-23 16:25:02.249 23082 23104 E StrictMode: java.lang.Throwable: Explicit termination method 'end' not called
10-23 16:25:02.249 23082 23104 E StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:184)
10-23 16:25:02.249 23082 23104 E StrictMode: 	at java.util.zip.Inflater.<init>(Inflater.java:82)
10-23 16:25:02.249 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2573)
10-23 16:25:02.249 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.getPrefixedName(ImapStore.java:842)
10-23 16:25:02.249 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher.getPrefixedName(ImapStore.java:2989)
10-23 16:25:02.249 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:902)
10-23 16:25:02.249 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher.internalOpen(ImapStore.java:2989)
10-23 16:25:02.249 23082 23104 E StrictMode: 	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3068)
10-23 16:25:02.249 23082 23104 E StrictMode: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by philipwhiuk** [comment]
So we need to work out the lifetime of an IMAP connection and what it's bound by to avoid leaks. I think the issue here is a IMAP connection not run in push (IDLE) mode. IMAP is inherently more complex because we support this feature.

For IMAP we have a pool of ImapConnection objects. 
Each ImapFolder attaches itself to a connection which it maintains a reference to.
The ImapFolderPusher extends ImapFolder which has a runnable that maintains the open connection.

We could just close down and released connections for any IMAP commands. The idle capability would then re-open / re-obtain a connection. That's very wasteful and sort of kills the point of IDLE to a degree.

We could instead radically change the IMAP folders so that there's two implementations instead of one and an extension, ImapFolderNotIdle and ImapFolderIdle. 

ImapNoIdle would have commands / meta-commands (so sync might be a meta command) create and destroy connections. Resolving StrictErrors would then be simply a matter of using the API correctly.

ImapIdle would have the connection owned by the folder, and the connection would be obtained for commands using a Thread locking model. The connection would be both created and destroyed by the IDLEing routine.
