### ISSUE TITLE
StrictMode: Preferences Storage SQLite StrictModeDiskReadViolation

### ISSUE THREAD

**Issue by lambdaupb** [k9mail/k-9#860]
It seems that DiskIO should be done on another Thread.

In case this was not a known-and-ignored warning, here the Stacktrace:

```
10-23 19:20:02.287 30354 30354 D StrictMode: StrictMode policy violation; ~duration=71 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=31 violation=2
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1043)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:597)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteConnection.setPageSize(SQLiteConnection.java:251)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:213)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1179)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1168)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:268)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at com.fsck.k9.preferences.Storage.openDB(Storage.java:44)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at com.fsck.k9.preferences.Storage.loadValues(Storage.java:177)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at com.fsck.k9.preferences.Storage.<init>(Storage.java:200)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at com.fsck.k9.preferences.Storage.getStorage(Storage.java:155)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at com.fsck.k9.Preferences.<init>(Preferences.java:44)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at com.fsck.k9.Preferences.getPreferences(Preferences.java:31)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at com.fsck.k9.K9.onCreate(K9.java:583)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4593)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.app.ActivityThread.access$1600(ActivityThread.java:154)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.os.Looper.loop(Looper.java:135)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:5294)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at java.lang.reflect.Method.invoke(Method.java:372)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
10-23 19:20:02.287 30354 30354 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by cketti** [comment]
It's known and has been ignored for a long time now. But that's no reason for not having an issue.
