### ISSUE TITLE
Crash when attempting to open a PGP/MIME encrypted email with an unknown key 

### ISSUE THREAD

**Issue by alexandre75** [k9mail/k-9#896]
When PGP provider doesn't own the key pair used to encrypt the email, K9 crashes with the following stacktrace if we attempt to open this email
```
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: main
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime: java.lang.IllegalStateException: Fragment MessageViewFragment{41e6ab50} not attached to Activity
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at android.app.Fragment.getLoaderManager(Fragment.java:1014)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.messageview.MessageViewFragment.startExtractingTextAndAttachments(MessageViewFragment.java:267)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.messageview.MessageViewFragment.onCryptoOperationsFinished(MessageViewFragment.java:262)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper.returnResultToFragment(MessageCryptoHelper.java:451)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptOrVerifyNextPart(MessageCryptoHelper.java:126)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoFinished(MessageCryptoHelper.java:447)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoSuccess(MessageCryptoHelper.java:430)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper.handleCryptoOperationSuccess(MessageCryptoHelper.java:413)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper.handleCryptoOperationResult(MessageCryptoHelper.java:372)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoOperationReturned(MessageCryptoHelper.java:346)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$400(MessageCryptoHelper.java:48)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper$7.onPostExecute(MessageCryptoHelper.java:333)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.fsck.k9.ui.crypto.MessageCryptoHelper$7.onPostExecute(MessageCryptoHelper.java:314)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at android.os.AsyncTask.finish(AsyncTask.java:631)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at android.os.AsyncTask.access$600(AsyncTask.java:177)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:153)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5299)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
11-13 17:58:35.039 16253-16253/com.fsck.k9.debug E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
11-13 17:58:35.087 452-471/? E/AppErrorDialog: Failed to get ILowStorageHandle instance
```
We should have some kind of message : "Unable to decrypt"

**Comment by alexandre75** [comment]
fixed by #588
