### ISSUE TITLE
Error negative SMTP reply : 550 5.5.0 Emetteur invalide. Invalid Sender. LPN104_415

### ISSUE THREAD

**Issue by chrisleb64** [k9mail/k-9#938]
Unable to send any messages since november with error smtp 550. server is smtp.laposte.net 
configuration SSL/TLS, port 465, normal authentication. No issue using gmail with the same configuration.

Error reported:

K9-Mail version: 5.006
Device make: LGE
Device model: LG-H815
Android version: 5.1
com.fsck.k9.mail.MessagingException: Unable to send message
at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:539)
at com.fsck.k9.mail.transport.SmtpTransport.sendMessage(SmtpTransport.java:495)
at com.fsck.k9.controller.MessagingController.sendPendingMessagesSynchronous(MessagingController.java:3563)
at com.fsck.k9.controller.MessagingController$20.run(MessagingController.java:3314)
at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
at java.lang.Thread.run(Thread.java:818)
Caused by: com.fsck.k9.mail.transport.SmtpTransport$NegativeSmtpReplyException: Negative SMTP reply: 550 5.5.0 Emetteur invalide. Invalid Sender. LPN104_415
at com.fsck.k9.mail.transport.SmtpTransport.checkLine(SmtpTransport.java:649)
at com.fsck.k9.mail.transport.SmtpTransport.executeSimpleCommand(SmtpTransport.java:690)
at com.fsck.k9.mail.transport.SmtpTransport.executeSimpleCommand(SmtpTransport.java:654)
at com.fsck.k9.mail.transport.SmtpTransport.sendMessageTo(SmtpTransport.java:521)
... 5 more

**Comment by s3b-** [comment]
This is not a k-9 issue, this is an issue on your server's side. k-9 just delivers the error message to you. 

https://www.google.com/webhp?#q=550+invalid+sender+smtp

**Comment by cketti** [comment]
Make sure your email address under 'Account settings > Sending mail > Composition defaults > Your email address' is correct.
