### ISSUE TITLE
K9 mail hangs up if the connection goes unused for over a minute

### ISSUE THREAD

**Issue by z28cueball** [k9mail/k-9#976]
This problem is happening on a Samsung running OS 4.4.4, and a Droid Turbo running OS 5.1.
This problem occurs using IMAP with both polling or IDLE.
If the connection is used every minute (either via e-mails coming in, going out, etc., or by a poll  or IDLE refresh), the connection is fine.  If the polling or IDLE refresh is set to anything longer than a minute, and no e-mails come in or go out, the connection stops working.
Once the connection has gone unused for over a minute, any attempt to do anything with the connection (poll, send e-mail, delete an existing email) will cause K9 mail to hang up (the application still responds, but it is stuck trying to communicate with the server).
I did force close K9 after waiting 25 minutes for it to give up trying to communicate with the server and/or throw an error.  Once it was force stopped and re-opened, the following error was in the error folder:
java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
	at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:592)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:556)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:485)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	at java.io.InputStream.read(InputStream.java:162)
	at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:149)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:234)
	at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:34)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:42)
	at com.fsck.k9.mail.store.ImapResponseParser.readResponse(ImapResponseParser.java:29)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.readStatusResponse(ImapStore.java:2775)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2925)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:862)
	at com.fsck.k9.mail.store.ImapStore$ImapFolderPusher$1.run(ImapStore.java:3151)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:185)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:553)
	... 14 more

**Comment by z28cueball** [comment]
Based on cketti's response to another poster, I have opened a bug report here:
https://groups.google.com/forum/#!topic/k-9-mail/5WGGmNNdw8Q

**Comment by cketti** [comment]
Sounds like your gateway kills idle connections after a very short timeout. It doesn't make sense to use IMAP IDLE in that case.

**Comment by z28cueball** [comment]
This is NOT invalid. My sever does NOT disconect idle clients as confirmed with computer clients and via telnet, as well as over a week of troubleshooting with the server company.

**Comment by Valodim** [comment]
did you check if your gateway does?

**Comment by z28cueball** [comment]
My mobile gateway?   No, they don’t.  This problem does not seem to happen with older Androids, either.  It occurs regardless of whether the phone is on 3G, 4G, or WiFi (tested with multiple internet providers), and the problem occurs with multiple e-mail providers.
